### ISSUE TITLE
Add configuration to skip the creation of .resx files without entries

### ISSUE THREAD

**Issue by FlorianDecker** [tom-englert/ResXResourceManager#1]
Hi!

We would like the possibility to skip the creation of empty resx files when importing from excel.

Our concrete use case is, that we are using country variant cultures and only a few of our resources actually need a country variant localization. Therefore, during the import there are a lot of empty .resx files added, which are going to stay empty and only clutter the solution or need to be removed manually.

Our use case could be fixed by an additional configuration entry in the "File Creation" category, with something like: "Do not create empty resource files.".

As we need this feature, we are going to implement this in a fork anways and provide the change in a pull request during the coming week. Are there any concerns/ideas you want to add?

**Comment by tom-englert** [comment]
I think during excel import this should be the default behavior, I wonder if we really need this to be configurable?

**Comment by tom-englert** [comment]
I think this is a bug and does not need any configuration - it should just verify accessibility of cultures that are not empty. See http://resxresourcemanager.codeplex.com/SourceControl/changeset/37674; will be synchronized with github soon.

**Comment by FlorianDecker** [comment]
Thanks for the quick response and the quick fix! 
Do you have an estimate when this fix will be released?

**Comment by tom-englert** [comment]
probably next weekend.
