### ISSUE TITLE
How to setup creating key in resource?

### ISSUE THREAD

**Issue by svatauli** [tom-englert/ResXResourceManager#10]
Hi all,

can you tell how can I setup key to: Namespace+ClassName+Property...

Thanks.

**Comment by tom-englert** [comment]
I assume you are talking about "move to resource", right?

Where would you get property from?

**Comment by tom-englert** [comment]
@svatauli: any more specific info what this is about?

**Comment by tom-englert** [comment]
Closed - no clue what this is about, and no more info provided.
