### ISSUE TITLE
Visual Studio 2017 crash when this plugin is enabled

### ISSUE THREAD

**Issue by Sebastian1989101** [tom-englert/ResXResourceManager#102]
Everytime I try to debug my Xamarin.Forms / Android project while this plugin is active, the whole Visual Studio 2017 crashes since the latest update of it. A fix would be great because I was using this plugin a lot... 

Maybe this is related: My project has currently 11 languages which each over 10.000 entries. But I don't understand why the whole studio crashes when I try to debug even when the ResxManager window is not open.. the plugin needs just to be active.

Edit: I have this problem on all of my 3 Windows mashines since I updated the Visual Studio 2017 to the latest version. And it crashes already in the compiling process.

**Comment by Insire** [comment]
Same here. Windows 10 Pro x64 with Visual Studio 2017 15.6.1.
Compiling a c# solution with 80 projects, will make VS hang. Waiting doesnt help either (waited 30mins++)

**Comment by tom-englert** [comment]
Duplicate of #97
