### ISSUE TITLE
No code generated

### ISSUE THREAD

**Issue by dmitrykarpenko** [tom-englert/ResXResourceManager#105]
If a resource names format is {name}.{language}.resx (contains dot between name and language), then those are displayed OK in ResX Resource Manager (as one instance for several languages), but no code is generated:
https://image.prntscr.com/image/q-jQUvXdTgaGq9Z50Lfseg.png
https://image.prntscr.com/image/B_AG0cfkSQah_M6Em6r-2A.png

On the other hand, code is generated after rename (to {name}-{language}.resx format), but ResX Resource Manager doesn't show several languages as one instance:
https://image.prntscr.com/image/3CznIGbER_KrGQtk3LzhWA.png
https://image.prntscr.com/image/10UmLx31QnuX0puNUUjOIw.png

That's probably happening due to the bug in the code generating tool (described here https://stackoverflow.com/questions/3314140/how-to-read-embedded-resource-text-file/31211830#31211830), so adding the ability to specify custom file name format (e.g. {name}-{language}.resx) should fix the issue.

**Comment by tom-englert** [comment]
The code is usually generated from the neutral language file, which is by convention {name}.resx.
This file is missing in your samples.
There is no bug in the code generator.
