### ISSUE TITLE
VS 15.6.2 - Standard header expected error when import from Excel

### ISSUE THREAD

**Issue by DanieleMazz** [tom-englert/ResXResourceManager#107]
When I try to import a configuration from an Excel file a messageBox appears with the error:
"Standard header expected."
The error occurs even if I try to export and immediately import the newly created file.
can you help me?
Thanks in advance

**Comment by tom-englert** [comment]
It works if you have changed and saved with Excel. Importing an unchanged file will be fixed in the next release.
