### ISSUE TITLE
Import from excel generates numbers instead of text

### ISSUE THREAD

**Issue by imarcu** [tom-englert/ResXResourceManager#108]
When importing a new excel file my result looks like this : 
![image](https://user-images.githubusercontent.com/7870152/37826528-6e1e141e-2e9c-11e8-8504-9e2559a1e56f.png)
instead of the text that is in the excel file on those columns.

I have checked the key and it maches, the column names are identitcal because the file i am importing is just an old export that was edited. I have applied the same format on the entire document just to be sure.

**Comment by tom-englert** [comment]
Can you share the excel file?

**Comment by imarcu** [comment]
can i add a file here ? 
this is a link from my drive
https://drive.google.com/file/d/1JbXJyJ60RxMbg02_vzYS30MTiZ7OWB5C/view?usp=sharing

when importing this i have this result 
![image](https://user-images.githubusercontent.com/7870152/37833742-c4a85f48-2eb4-11e8-87b0-247c8d9c6cb3.png)
