### ISSUE TITLE
Feature request for xml and json string files

### ISSUE THREAD

**Issue by dolphinsd** [tom-englert/ResXResourceManager#109]
Microsoft recommends to use xml or json strings files to manage strings as it easy to read, portable across platforms, etc. It easy to implement.

**Comment by tom-englert** [comment]
.resx files **ARE** xml - so what is this request about?

**Comment by tom-englert** [comment]
@dolphinsd any adds to this?

**Comment by dolphinsd** [comment]
Have you try to edit those xml files by hand? I am talking about simple xml/json file with simple structure. For example: 
<?xml version="1.0" encoding="utf-8" ?>
<localizationDictionary culture="en">
  <texts>
    
    <text name="HomePage" value="Home page" />
    <text name="AboutUs" value="About us" />
 
  </texts>
</localizationDictionary>

**Comment by tom-englert** [comment]
do you think of something like in #31?

**Comment by tom-englert** [comment]
closed: request unspecific, no feedback
