### ISSUE TITLE
Scripting error in V 1.0.0.99

### ISSUE THREAD

**Issue by vsmahesh** [tom-englert/ResXResourceManager#11]
**I was trying the new version of scripting (1.0.0.99) and I am getting the following error. Its working fine in 1.0.0.96. It could be introduced between 1.0.0.97-99.**

New-Object : Exception calling ".ctor" with "0" argument(s): "No exports were found that match the constraint: 
    ContractName    ResXManager.Scripting.SourceFilesProvider
    RequiredTypeIdentity    ResXManager.Scripting.SourceFilesProvider"
At C:\GetContents\Scripting\Sample.ps1:8 char:11
+ $myhost = New-Object -TypeName 'ResXManager.Scripting.Host'
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 
You cannot call a method on a null-valued expression.
At C:\GetContents\Scripting\Sample.ps1:11 char:1
+ $myhost.Load($solutionFolder)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
All entires: 0
Changes compared to snapshot:
You cannot call a method on a null-valued expression.
At C:\GetContents\Scripting\Sample.ps1:36 char:1
+ $myhost.LoadSnapshot($snapshot)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At C:\GetContents\Scripting\Sample.ps1:39 char:17
+     Where-Object { $_.Values.GetValue($neutralCulture) -ne $_.SnapshotValues.GetVal ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Number of changes: 0
Now you can modify the excel file:  C:\temp\export\Test.xlsx: 

Importing modified excel file
You cannot call a method on a null-valued expression.
At C:\GetContents\Scripting\Sample.ps1:64 char:1
+ $myhost.ImportExcel($excelFileName)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At C:\GetContents\Scripting\Sample.ps1:66 char:1
+ $myhost.Save()
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Create a new snapshot with the latest data? (Y/N): Y
Updating snaphot C:\temp\export\1.snapshot
You cannot call a method on a null-valued expression.
At C:\GetContents\Scripting\Sample.ps1:72 char:2
+     $snapshot = $myhost.CreateSnapshot()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Done: 
You cannot call a method on a null-valued expression.
At C:\GetContents\Scripting\Sample.ps1:77 char:1
+ $myhost.Dispose()
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by tom-englert** [comment]
Fixed in v1.1
