### ISSUE TITLE
Exception when trying to add a new resource file

### ISSUE THREAD

**Issue by FortegaITSolutions** [tom-englert/ResXResourceManager#111]
Hi,

When I add a new language and try to add translation, I am asked if I want to add the resource file to the project. When I press 'Yes', I get the following exception: 'error adding the new resource file' (see screenshot) (by the way, the stacktrace mentions C:\Agent, but this folder does not exist on my pc)

I am not able to add new translations at the moment.

![image](https://user-images.githubusercontent.com/2579974/37976296-7a61383a-31e1-11e8-850b-9255965cfb79.png)

**Comment by tom-englert** [comment]
This is an error message from VS (EnvDTE.ProjectItem) - sometimes restarting VS helps.
Does this only happen with one specific project, or with all projects in the solution?
Maybe changing the File creation configuration helps?

**Comment by FortegaITSolutions** [comment]
Restarting VS sometimes helps... Where do I find the File creation configuration?

**Comment by tom-englert** [comment]
On the configuration page

**Comment by tom-englert** [comment]
@FortegaITSolutions could you solve this?

**Comment by tom-englert** [comment]
@FortegaITSolutions any news on this?

**Comment by tom-englert** [comment]
closed: not reproducible and no feedback

**Comment by FortegaITSolutions** [comment]
I'm sorry for the lack of feedback, @tom-englert 
I regularly get this exception when trying to import an xlsx-file for a new language.
However, restarting visual studio works most of the time.

**Comment by tom-englert** [comment]
So there is nothing much that I could do here, if Visual Studio does not let me add the new file.
If restarting helps, at least you have a workaround.
