### ISSUE TITLE
Main page blank. 

### ISSUE THREAD

**Issue by Markallanlevy** [tom-englert/ResXResourceManager#113]
I am running VS 2015, but also saw same issue on VS 2017.
I have tried to follow the other threads that appear to be related to this, but making those changes did not do anything. 

![image](https://user-images.githubusercontent.com/38045728/38261207-323c9f92-372f-11e8-9076-64d8b92f804c.png)

**Comment by Markallanlevy** [comment]
Runtime Version: v4.0.30319

**Comment by tom-englert** [comment]
@Markallanlevy can you try the latest version from http://vsixgallery.com/

**Comment by Markallanlevy** [comment]
WORKING!!!

Thanks so much!
