### ISSUE TITLE
neutral de

### ISSUE THREAD

**Issue by a-swoboda** [tom-englert/ResXResourceManager#114]
It is not possible to add the neutral de Language

**Comment by tom-englert** [comment]
@a-swoboda Please add a proper description of your problem.

**Comment by a-swoboda** [comment]
When trying to add the neutral de-Language which has only de as Name (not de-DE or de-AT) this is not possible,
the resource should have the name {Name}.de.resx.
With the command “Add new Language” you get the window to select a language, but de is always replaced with de-DE.
Even if this resource is already existing it is not recognized, with cs, en, eu this works.

Von: tom-englert <notifications@github.com>
Gesendet: Donnerstag, 05. April 2018 10:41
An: tom-englert/ResXResourceManager <ResXResourceManager@noreply.github.com>
Cc: Swoboda Albrecht <A.Swoboda@pimpel.at>; Mention <mention@noreply.github.com>
Betreff: Re: [tom-englert/ResXResourceManager] neutral de (#114)


@a-swoboda<https://github.com/a-swoboda> Please add a proper description of your problem.

**Comment by a-swoboda** [comment]
Addition:
This works in the standalone, but not from VS(2013)!

**Comment by tom-englert** [comment]
It works fine, unless you already have a "de" resource

**Comment by a-swoboda** [comment]
Hello Tom,

thanks for the answer, saved my time. :-)
(With the .cs.resx file it worked also if the file was already existing)

regards
albrecht

**Comment by tom-englert** [comment]
😄
