### ISSUE TITLE
Does the reference within WPF not count in the reference number?

### ISSUE THREAD

**Issue by maikebing** [tom-englert/ResXResourceManager#115]
`    xmlns:p="clr-namespace:SteveCadwallader.CodeMaid.Properties">`

`   <CheckBox Content="{x:Static p:Resources.CleanupActiveDocument}" IsChecked="{Binding CleanupActiveCode}" />`

**Comment by tom-englert** [comment]
Yes, it should:
![image](https://user-images.githubusercontent.com/10229954/38468377-0b4e93bc-3b45-11e8-9ef2-1d972c4f8cb6.png)

**Comment by maikebing** [comment]
Thanks!
