### ISSUE TITLE
Text Change Suggestions in Wiki

### ISSUE THREAD

**Issue by vsmahesh** [tom-englert/ResXResourceManager#12]
Could you change the word Downloads page to Release page since download page no longer exists? This is bit confusing for the end user.

**Pages needs to be changed**
https://github.com/tom-englert/ResXResourceManager/wiki/Installation
https://github.com/tom-englert/ResXResourceManager/wiki/Scripting

Also you could add hyperlink to the release page for better usability. I don't know how to create a pull request for the wiki; otherwise I could have done that.

**Comment by tom-englert** [comment]
OK, fixed
