### ISSUE TITLE
Supress "missing translation" warnings from specific files or projects

### ISSUE THREAD

**Issue by ImrePyhvel** [tom-englert/ResXResourceManager#120]
I have a project with N localized languages. On build, ResXManager shows me warnings for every missing translations. While some parts of application should support all N languages, some other parts are ever user only in subset of languages and hence we are not adding those translations. Meaning, we have a few "missing translation"-warnings we care about among plenty of "missing translation" warnings which are by design. 

In addition, I have a resx file in test project to test some dynamic lookups from ResourceManagers. Obviously it does not have all language resources as they are irrelevant for the test scenarios, and, they generate a lot of junk warnings.

I know that Configuration tab allows me to suppress all warnings from being generated. But since it is a useful feature, I'd like to suppress such warnings only on chosen parts of application. 

Is this possible? How?

**Comment by ImrePyhvel** [comment]
I found that a partial solution is to adjust the "File exclusion filter" regular expression under "Configuration" tab. This also removes the resources from "Main" view, which is ok in some scenarios and less ok for others.

The general question of options for suppression of warnings (without total exclusion) still stands.

**Comment by tom-englert** [comment]
@ImrePyhvel you can simply switch off warnings on the configuration tab, or mark all respective entries as "Invariant"

**Comment by ImrePyhvel** [comment]
Switching off all warnings was not what I needed, but your hint about marking key as "Invariant" was what I was looking for. Found there's even a small wiki page about the feature: [wiki/Invariant-Strings](https://github.com/tom-englert/ResXResourceManager/wiki/Invariant-Strings).

**Comment by tom-englert** [comment]
😃
