### ISSUE TITLE
@Invariant 

### ISSUE THREAD

**Issue by McOldSchool** [tom-englert/ResXResourceManager#125]
Hey Tom, hey folks,
I run into a little, but -over time- very annoying behavior between the .resx-files and MSVS. Furthermore, I duno where it is mostly related to, so I just open an issue here.

If I mark an entry as ["@Invariant"](https://github.com/tom-englert/ResXResourceManager/wiki/Invariant-Strings) and some work on the related project file is done, all those comments are (sometimes) going to be delete.
Is there any setting in MSVS 2017 or workaround to fix this s**t - jep it's driving me nuts meanwhile :(

Thanks for any ideas/solution in advance - since I haven't found anything online.

**Comment by tom-englert** [comment]
@McOldSchool What is the "related project file"? Are you maybe talking about WinForms?

**Comment by tom-englert** [comment]
@McOldSchool any input on this?

**Comment by McOldSchool** [comment]
Hey Tom,
sorry for the delay. Yep it's a vb-file with a "System.Windows.Forms.Form" inside of it are some DevEx parts.

Whenever I mark an entry as  <value>.Properties.Mask.EditMask to @Invariant, everything is fine until someone is working on the vb again. After the next save, those Invariants are lost (saved in the main.resx which is showing those grayed lines in ResXResourceManager.

**Comment by tom-englert** [comment]
There is some special handling to preserve the invariant when you change WinForms controls via the designer. (https://github.com/tom-englert/ResXResourceManager/blob/master/ResXManager.Model/ResourceEntity.cs#L369) Is your resource file properly nested under the form.vb and beside the form.designer.vb?

**Comment by tom-englert** [comment]
Also maybe 'someone' has not installed ResXManager - in this case ResXManager can't preserve the comments.

**Comment by McOldSchool** [comment]
Yes the nesting seems to be fine, but I'll have to check if the ResXManager is installed on every coworkers PC (during the next week).
But I fear there are most likely some missing since the project is a little bigger and addons/-ins are... but it this was VS is not 64bit yet (and won't be for a long time).
=> The stand-alone version won't keep track of it? (Has to be opened?)

**Comment by tom-englert** [comment]
The standalone version does not have any information about the project structure, it's just working on files , it can't track this.

**Comment by McOldSchool** [comment]
Good to know - and sad that MS overrides comments in the first place.

I'll close this issue, because everything is working as it "can" :)
