### ISSUE TITLE
Neutral language

### ISSUE THREAD

**Issue by nolme** [tom-englert/ResXResourceManager#126]
Hi,

(first : you extension is GREAT and works very well)

During compilation I have warning like this :
'label1.Text.en : Missing translation'

In you extension I see Neutral, English, French. I need for the moment to use only 2 languages. So how can I avoid duplicate between Neutral & one of the other language (and remove the warning message ?

Thanks,
Vincent

**Comment by tom-englert** [comment]
see https://github.com/tom-englert/ResXResourceManager/wiki/Invariant-Strings

**Comment by tom-englert** [comment]
the neutral files are `<name>.resx`, so you have to rename all `<name>.fr.resx` to make them the neutral ones. Or switch to cell selection and copy all french to the neutral column, then remove all .fr.resx files.
