### ISSUE TITLE
Problems with Jetbrains.Annotations.dll reference not found, stand-alone application does not work at all.

### ISSUE THREAD

**Issue by mwedmark** [tom-englert/ResXResourceManager#130]
The stand-alone tool cannot run on any tested computer I'v tried. Not even with Visual Studio 2017 installed on the system.

![image](https://user-images.githubusercontent.com/2123085/40416730-45f8cce2-5e7e-11e8-831a-4fa08297bf2e.png)

I don't know in which version this started but on a system missing Jetbrains.Annotations.dll in the GAC the stand-alone-tool cannot be used. I think you need to make a selection when building to either have it as  a  internal resource OR make it optional otherwise this will be a hassle for your users.

I managed to trouble-shoot, download the file from nuget package, start the "VS x86 Native Tools Command Prompt" as Administrator, run '**gacutil**' and register the Jetbrains.Annotations.dll in GAC. That works as a temporary work-around until a new release is done.

**Comment by tom-englert** [comment]
Fixed
