### ISSUE TITLE
Feature request - filter just blanks

### ISSUE THREAD

**Issue by exuser** [tom-englert/ResXResourceManager#131]
Hi Tom,

I am a big fan of ResXResourceManager and would like to say congratulations to you and all contributors! Keep up the good work!

I have a request if it is possible - filter blanks. Add the ability to simply show blank rows in a language. Current filters (column headers) need a string obviously, a white space does not do the job either.

In case something like this already exists, please let me know (i have not spotted any).

Thanks
Tony

**Comment by tom-englert** [comment]
Hi Tony,

the easiest way is to click on the column header - the table will be sorted by this column, and all blank rows will be on the top.

If you really need to filter, just use the regular expression "^$".

**Comment by exuser** [comment]
Thanks Tom

all the best
