### ISSUE TITLE
Move to resources not working good

### ISSUE THREAD

**Issue by RaduDtr3s** [tom-englert/ResXResourceManager#135]
Hello, when I have an text in an Html and I want to use the option Move to Resources, the code that it replaces is like the one in the picture
![captura](https://user-images.githubusercontent.com/39994659/41040350-74c8eb6e-699c-11e8-9d21-d8b45523cf9b.PNG)
 in stead of the correct characters. Is there same way to fix it?

**Comment by tom-englert** [comment]
That's exactly like it's configured:

![image](https://user-images.githubusercontent.com/10229954/41040508-e7151fa8-699c-11e8-8beb-437299af85c1.png)

isn't that right? I just copied that from s.o. who told me it should be like this...

**Comment by RaduDtr3s** [comment]
No, it isn't right, it has to be server side code, it sould be like this
![captura](https://user-images.githubusercontent.com/39994659/41041449-611dfa8e-699f-11e8-9851-aaa142034b32.PNG)

**Comment by tom-englert** [comment]
maybe it should be `< >` instead of `&lt; &gt;`?

**Comment by RaduDtr3s** [comment]
Yes and the "=" instead of the "$", with the "$" it does not compile

**Comment by tom-englert** [comment]
So you can fix that for yourself on the configuration tab. I will update the default, so it will be right in the next release.

**Comment by RaduDtr3s** [comment]
Where can I find the configuration tab?

**Comment by RaduDtr3s** [comment]
Ah ok I found it

**Comment by tom-englert** [comment]
😄

**Comment by tom-englert** [comment]
so what about this pattern: `Text='<%$ Resources:Resource, WizardStep1Resource1 %>'`?
(https://msdn.microsoft.com/en-us/library/fw69ke6f.aspx#Anchor_4, https://stackoverflow.com/questions/7405605/access-global-resources-in-an-asp-net-control)
Doesn't that work?

**Comment by RaduDtr3s** [comment]
In ascx files yes (C#) but in aspx files (Vb) it does not work

**Comment by tom-englert** [comment]
OK, I've added multiple patterns, so you can select the one that works for you.

**Comment by RaduDtr3s** [comment]
Okey perfect. Thank you!
