### ISSUE TITLE
CSV import & export

### ISSUE THREAD

**Issue by JFMG** [tom-englert/ResXResourceManager#136]
Could we get a possibility to import and export CSV files?

The advantages of CSV files are that it is easier to show the difference in a version control system and that you can edit CSV with a lot of applications like Excel, Numbers, Open Office and more.

**Comment by tom-englert** [comment]
Import/Export via GUI or just via script?

**Comment by JFMG** [comment]
Via GUI, I'd say where currently the Excel export/import is

**Comment by tom-englert** [comment]
can you try the latest build from http://vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a/ ?

**Comment by JFMG** [comment]
I just made a simple code review. Not sure how to test it with Visual Studio

**Comment by tom-englert** [comment]
Just switch Export Mode to Text on the configuration tab
