### ISSUE TITLE
VS 2015 - Converting Issue/Question

### ISSUE THREAD

**Issue by AJFiori** [tom-englert/ResXResourceManager#137]
I downloaded the extension to VS and did the conversion from English to French (Canadian). When it did convert, I noticed not everything got converted. I went through and manually converted the ones that needed to be. After that I thought maybe it was the extension, so I downloaded the StandAlone App and tested with a different language. The same issue occurred. I am Connecting through an Azure key. Would you have an idea what could have caused the issue? Here is an example:

![image](https://user-images.githubusercontent.com/13458830/41064304-2de36a5a-69a9-11e8-8878-0e1c32647d0a.png)

As you can see it converted some but skipped others. Would it because the numbers are not in order from 1 - 16, so it gets confused when iterating through?

**Comment by tom-englert** [comment]
Depends on the translation service, usually it will provide various alternatives. 
I don't know why Azure reports "Custom 11" with a higher rank than the correct translation, you have to report this to the Azure Service.
![image](https://user-images.githubusercontent.com/10229954/41084011-356ab47e-6a33-11e8-9dbf-e632d9798ef1.png)

**Comment by AJFiori** [comment]
Ahhh alright, Thank you
