### ISSUE TITLE
RESX sort option to sort thesame way as in the UI

### ISSUE THREAD

**Issue by carloscs** [tom-englert/ResXResourceManager#138]
I really like the way resources are sorted in the UI: split by first underscore(s?) and sort by left part, right part.

Could we have an option to sort the RESX the same way please [maybe a checkbox "group by ResourcePrefix] :

BaseResource
BaseResource_One
BaseResource_Two
BaseResource_...
BaseResourceWithSuffix
BaseResourceWithSuffix_One
BaseResourceWithSuffix_Two
BaseResourceWithSuffix...

**Comment by tom-englert** [comment]
What exactly do you mean by "resources are sorted in the UI"? 
Your sample is a simple alphabetical sort, no special treatment of underscores...

**Comment by carloscs** [comment]
Hmm, you're right, that's the alphabetical sort. Looking at the RESX confused me, made me think underscore sorted after letters...

But then... what's the sort in the RESX file? In settings I tried both "Sort using OrdinalIgnoreCase" (my original setting) and "Sort using InvariantCultureIgnoreCase" and it's sorting letters before underscores:

BaseResource
BaseResourceWithSuffix
BaseResourceWithSuffix_One
BaseResourceWithSuffix_Two
BaseResourceWithSuffix...
BaseResource_One
BaseResource_Two
BaseResource_...

Any ideas?

Tx.

**Comment by tom-englert** [comment]
So you tried two out of three, now guess what the correct setting is? :smirk: 
UI is always using CurrentCulture(IgnoreCase).
