### ISSUE TITLE
SortFileContentOnSave does not seem to work

### ISSUE THREAD

**Issue by gpreseau** [tom-englert/ResXResourceManager#140]
I have the option to sort the RESX files when saving checked in the configuration for a specific solution.
When I open a form, make a change (like adding a label) and then save, the resx files associated to the form are not sorted.

**Comment by tom-englert** [comment]
This feature sorts the content after changing it using ResXManager, it has no effect when changing a resx file with a different editor, like the WinForms designer...

**Comment by gpreseau** [comment]
Oh! Ok!
Thanks for the clarification!
