### ISSUE TITLE
Crashes when solution includes files with too long paths

### ISSUE THREAD

**Issue by R0nd** [tom-englert/ResXResourceManager#144]
> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
> 
>    at System.IO.PathHelper.GetFullPathName()
> 
>    at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
> 
>    at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
> 
>    at System.IO.Path.GetFullPathInternal(String path)
> 
>    at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
> 
>    at System.IO.FileInfo..ctor(String fileName)
> 
>    at tomenglertde.ResXManager.VSIX.DteSourceFilesProvider.<>c__DisplayClass8_0.<get_DteSourceFiles>b__0(DteProjectFile p) in C:\Agent\_work\9\s\ResXManager.VSIX\DteSourceFilesProvider.cs:line 57
> 
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
> 
>    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
> 
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
> 
>    at tomenglertde.ResXManager.VSIX.DteSourceFilesProvider.get_SourceFiles() in C:\Agent\_work\9\s\ResXManager.VSIX\DteSourceFilesProvider.cs:line 41
> 
>    at tomenglertde.ResXManager.View.Visuals.ResourceViewModel.<BeginFindCodeReferences>_Throttle_Fody_Method() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceViewModel.cs:line 530
> 
>    at TomsToolbox.Wpf.DelegateCommand.Execute(Object parameter)
> 
>    at TomsToolbox.Wpf.Converters.ConfirmedCommandConverter.CommandProxy.Execute(Object parameter)

**Comment by tom-englert** [comment]
Doesn't look like a crash, but just an error message - when exactly does this occurre?

**Comment by R0nd** [comment]
It occurs straight away when opening resxmanager
________________________________

**Comment by tom-englert** [comment]
OK, and what exactly is "It"?

**Comment by R0nd** [comment]
"It" is the error message in the original post. I'd say it qualifies as a crash because the extension window closes after the error message is dismissed. The error occurs when the currently opened solution contains files with absolute paths over 260 symbols long.

**Comment by tom-englert** [comment]
I tried to reproduce, but I even could not open such a project in VS - how did you manage this?
