### ISSUE TITLE
Export to excel also the index of the entry in resx file

### ISSUE THREAD

**Issue by Spamme1** [tom-englert/ResXResourceManager#147]
I haven't found how to export to excel also the index of the entry in resx file. It isn't that we want to change it, but to help the translators to understand the context, we make screenshots of the UIs and we put a number next to the texts, so that the translators can check where the text appears in the UI.
Therefore it would be nice to have these numbers in the excel export, just to use them as references in the UI screenshots.

**Comment by tom-englert** [comment]
Maybe you can use the MultipleSheet export mode - here every sheet corresponds to one .resx, and the row should correspond to the index.

**Comment by Spamme1** [comment]
@tom-englert 
Maybe, at the moment we select all the entries in the grid view in the application and we paste them in excel, practically we do a manual export of the data. There are three good reasons, why we do it:
1. In the export is missing the index of the resource, which we want to use in the UI screenshots
2. The export contains also the "comment" fields, which we don't use and don't want in the excel
3. The sequence of the exported resources is different from the one in the UI

**Comment by tom-englert** [comment]
@Spamme1 
1. Resources are key-value pairs, the index has no meaning. Using the index instead of the key is a design flaw.
2. You can hide the comments in the UI and export only the selection.
3. Of course, because you can sort the UI by any column.

**Comment by Spamme1** [comment]
@tom-englert 
I know that the the resources are key-value pairs, the idea of exporting the index it is just to have an unique number to add to the UI screenshots to show to the translators, where the texts appear on the UI and nothing more. It isn't that we want to change them and import them back, not at all.

**Comment by tom-englert** [comment]
If you think this is useful, you can submit a PR
