### ISSUE TITLE
"Delete" is incomplete

### ISSUE THREAD

**Issue by JRi90** [tom-englert/ResXResourceManager#148]
When I use "Delete", only the entries from the language files are deleted. The entry in the neutral file still exists.

Is this a bug or a feature? :)

**Comment by tom-englert** [comment]
Maybe you have cell-selection active? In this case it will of course delete the selected cells only.

**Comment by JRi90** [comment]
Yes, cell-selection is active. I'm going to disable the option.

It is confusing and unintuitive when you select the row with a right-click on the first column, and then only the cells of the languages are emptied during the delete. :)

**Comment by JRi90** [comment]
Would it be an option to call it "Clear" when cell-selection is active?

**Comment by tom-englert** [comment]
And maybe just disable it if any of the fixed columns are selected...

**Comment by tom-englert** [comment]
UX should be improved here...
