### ISSUE TITLE
Items are not created in all ResX Files

### ISSUE THREAD

**Issue by jacke9999** [tom-englert/ResXResourceManager#149]
If i create an Item, not all (mostly one or two) ResX-Files are modified. 
I have 15 Languages. If i create a new Item, only these ResX-Files are modified, where i put in a Text manually. All other files are not modified. So i cannot see the changes of the separate files.

**Comment by tom-englert** [comment]
Check "Create all resource files..." on the configuration tab.

**Comment by jacke9999** [comment]
I have checked this option, but you see at the screenshot, only three files are affected. Not all of them.
![2018-07-03_11h49_34](https://user-images.githubusercontent.com/40791057/42212744-88d6ca08-7ea6-11e8-9aa9-9f1ec760f953.jpg)
![2018-07-03_11h52_23](https://user-images.githubusercontent.com/40791057/42212845-ce869b50-7ea6-11e8-881a-a9a949c07bec.jpg)

**Comment by jacke9999** [comment]
Maybe an Option in an future version. This would be very helpful for version control!!

**Comment by tom-englert** [comment]
I don't see too much value in this, but maybe you want to submit a PR?
