### ISSUE TITLE
Use Detect Code References to fill resx file

### ISSUE THREAD

**Issue by vdurante** [tom-englert/ResXResourceManager#15]
Hey. Beforehand I would like to thank you for this amazing tool. It is incredible!

I Noticed the Detect Code References in configuration. I would like to know if it is possible to detect keys using a regex and automatically add them to the resx files. I know there is a Move to Resource option, but I would like to do it automatically.

Thanks in advance

**Comment by tom-englert** [comment]
But if you already have keys in your source, what would these keys reference if there is not already a resource for it?
Maybe you want to detect strings and automatically convert them to resources?

**Comment by tom-englert** [comment]
@vdurante any more input on this?

**Comment by vdurante** [comment]
Thank you for the response.

Yes, it would be a string detection. But since I am working with Asp.Net
Boilerplate, all strings follow the same pattern. Something like:

@L("MyString") for razor views
L("MyString") in controllers
abp.localization.localize("MyString") in JavaScript

I did succeed building a regex that identifies strings for counting inside
the manager. But I would like to do somethin different: identify these
cases and add them to the resource manager.

I noticed I can right click the string and add to the resource, but I would
like to identify automatically all cases.

I don't know if it is possible at the moment. If it is not I will do it
manually.

Thanks in advance.

**Comment by tom-englert** [comment]
Having this as a global feature is too complex, especially generating a useful key from the string is challenging - and everyone would have different requirements.

If you already have a working regex, you can easily use the [scripting module](https://github.com/tom-englert/ResXResourceManager/releases/latest) and write a Power Shell script to do the task.
