### ISSUE TITLE
Warnings in Visual Studio (2017)

### ISSUE THREAD

**Issue by Intelli-Soft** [tom-englert/ResXResourceManager#150]
Hey
First of all, I want to tell you, that this plugin is really cool stuff! - THX

I have a Resx file, where one Value has an empty string as wanted text. In all translations
Now, I get a warning (this is okay), but I get as many warnings, as properties are in the resx file.
In my case, I have 23 properties within the RESX file. So, I get 23 warnings, for a missing translation, but it is only the one, which is wanted.
THX

**Comment by tom-englert** [comment]
@Intelli-Soft what are "properties within the RESX file"?

**Comment by Intelli-Soft** [comment]
The resorce keys – sorry
Thx
Gesendet von meinem Windows 10 Phone

________________________________
Von: tom-englert <notifications@github.com>
Gesendet: Thursday, July 5, 2018 11:21:58 AM
An: tom-englert/ResXResourceManager
Cc: Harald Bacik; Mention
Betreff: Re: [tom-englert/ResXResourceManager] Warnings in Visual Studio (2017) (#150)


@Intelli-Soft<https://github.com/Intelli-Soft> what are "properties within the RESX file"?

**Comment by tom-englert** [comment]
I get exactly one warning per empty cell. Can you post a screen shot?

**Comment by Intelli-Soft** [comment]
Hey
Sure – I hope this works, when I embed the picture here:
[cid:image001.png@01D41495.A43F1FF0]

Von: tom-englert <notifications@github.com>
Gesendet: Donnerstag, 5. Juli 2018 12:10
An: tom-englert/ResXResourceManager <ResXResourceManager@noreply.github.com>
Cc: Harald Bacik <h.bacik@intelli-soft.at>; Mention <mention@noreply.github.com>
Betreff: Re: [tom-englert/ResXResourceManager] Warnings in Visual Studio (2017) (#150)


I get exactly one warning per empty cell. Can you post a screen shot?

**Comment by tom-englert** [comment]
@Intelli-Soft: no, there is no image embeddd

**Comment by tom-englert** [comment]
Looks like your neutral column is not visible, but empty for all entries.

**Comment by Intelli-Soft** [comment]
Okay. – So, it means I must set a neutral language. – Can I set the “de-at” as neutral anyhow, or do I have to copy all values from de-at to neutral?

THX

Von: tom-englert <notifications@github.com>
Gesendet: Freitag, 6. Juli 2018 14:40
An: tom-englert/ResXResourceManager <ResXResourceManager@noreply.github.com>
Cc: Harald Bacik <h.bacik@intelli-soft.at>; Mention <mention@noreply.github.com>
Betreff: Re: [tom-englert/ResXResourceManager] Warnings in Visual Studio (2017) (#150)


Looks like your neutral column is not visible, but empty for all entries.

**Comment by tom-englert** [comment]
you can just rename or copy the ???.de-at.resx file to ???.resx

**Comment by Intelli-Soft** [comment]
Perfect! – THX a lot – You can close this “issue” – What wasn’t any



Von: tom-englert <notifications@github.com>
Gesendet: Freitag, 6. Juli 2018 16:07
An: tom-englert/ResXResourceManager <ResXResourceManager@noreply.github.com>
Cc: Harald Bacik <h.bacik@intelli-soft.at>; Mention <mention@noreply.github.com>
Betreff: Re: [tom-englert/ResXResourceManager] Warnings in Visual Studio (2017) (#150)


you can just rename or copy the ???.de-at.resx file to ???.resx
