### ISSUE TITLE
Enhancement - Move to resource dialog box

### ISSUE THREAD

**Issue by JBaltika** [tom-englert/ResXResourceManager#151]
Hi Tom,

Would it be possible to add this simple enhancement to "Move to resource" dialog box. Essentially, add checkbox with value stored in user setting and depending on value generate in dialog full resource key [{File}_{Method}_{ResourceKey}]  or short version [{ResourceKey}]. What do you think? It would help as greatly as we need shorten key each time ... Thanks!

![move-to-resource-dialog-box](https://user-images.githubusercontent.com/1755340/42419359-4c377334-8281-11e8-940b-4c4c4a26df07.png)

**Comment by tom-englert** [comment]
Improved in 1.24

**Comment by JBaltika** [comment]
Hi Tom,
I just installed latest version 1.24.1179 and don't see any changes ... Did i missed something?

**Comment by JBaltika** [comment]
Awesome ! Thanks
