### ISSUE TITLE
VB.NET project path issue

### ISSUE THREAD

**Issue by DominickM324** [tom-englert/ResXResourceManager#152]
When using move to resource in a VB.NET solution the Code reference is only a drop-down and forces the "My Project" into the reference with a leading space. This of course generates an error in the code and has to be manually edited every time to remove the " Project" portion to correct the issue.

Originally injected:  WindowsApp1.My Project.Resources.Form1_Form1_Load_ThisIsATest

Has to be manually edited everytime to : 
 WindowsApp1.My.Resources.Form1_Form1_Load_ThisIsATest

Which corrects the issue and gives a valid reference to the resource.  I am attaching some images to show the issue.
![movetoresourcesolutionstructure](https://user-images.githubusercontent.com/41126857/42593869-37765070-8513-11e8-953f-8a7a0ffc9176.png)
![movetoresource3](https://user-images.githubusercontent.com/41126857/42593870-3786ef02-8513-11e8-8abf-42e64b2d4a65.png)
![movetoresource2](https://user-images.githubusercontent.com/41126857/42593871-37957478-8513-11e8-853f-8aca44f032c6.png)
![movetoresource1](https://user-images.githubusercontent.com/41126857/42593872-37a94e1c-8513-11e8-9335-b75810cc20ba.png)

**Comment by DominickM324** [comment]
Is there a reason this was closed without any kind of response????

**Comment by DominickM324** [comment]
Never mind I see where you updated the source with a fix. Any timeline when the next release is with this update? Working on massive application update that has thousands of resources that need to be added.

**Comment by tom-englert** [comment]
Maybe next weekend
However you can use the latest build from http://vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a/ until then

LG
Tom
________________________________
Von: DominickM324<mailto:notifications@github.com>
Gesendet: ‎12.‎07.‎2018 16:35
An: tom-englert/ResXResourceManager<mailto:ResXResourceManager@noreply.github.com>
Cc: tom-englert<mailto:mail@tom-englert.de>; State change<mailto:state_change@noreply.github.com>
Betreff: Re: [tom-englert/ResXResourceManager] VB.NET project path issue (#152)


Never mind I see where you updated the source with a fix. Any timeline when the next release is with this update? Working on massive application update that has thousands of resources that need to be added.
