### ISSUE TITLE
'' is an invalid xml:space value.

### ISSUE THREAD

**Issue by exuser** [tom-englert/ResXResourceManager#157]
Hi there

when trying to export all to Excel, it fails with this error message:

'' is an invalid xml:space value.

I am trying to understand if this means there are apostrophes in  Key perhaps, but there are none... i have looked at the resx files individually.

Any thoughts?

![2018-07-31_17-36-18](https://user-images.githubusercontent.com/39601209/43473735-e31d1b90-94e8-11e8-8975-1b23fcb5b926.png)

**Comment by tom-englert** [comment]
No idea, can you post a sample?

**Comment by tom-englert** [comment]
@exuser any input on this?

**Comment by tom-englert** [comment]
closed, no feedback
