### ISSUE TITLE
Is there a way to add a line break?

### ISSUE THREAD

**Issue by vbaskaran-hk** [tom-englert/ResXResourceManager#159]
Just recently downloaded the software and am very impressed.  Great job!

This is really more of a question than an issue.  Posting it here as I could not find an answer elsewhere.  

Is there a way to add line break for some of the translated values.  I have tried "\n", SHIFT-ENTER, ENTER etc.  None of them seem to work.

Any help will be greatly appreciated.

**Comment by tom-englert** [comment]
It's CTRL-ENTER, all other combinations were already in use by the grid.
Alternatively you can edit in the resizeable text box right to the toolbar (like in Excel). Here you can just type ENTER.

**Comment by vbaskaran-hk** [comment]
Thank you.  That worked out very well.  Once again, this is a wonderful product and it saved me a lot of effort and time.

**Comment by tom-englert** [comment]
If you like it, you can share it here: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
:smile:
