### ISSUE TITLE
Stand-alone version for translators

### ISSUE THREAD

**Issue by jerone** [tom-englert/ResXResourceManager#162]
For our projects we've been using XLF files for translations. To convert the XLF files to Resx files, we were using [Multilingual App Toolkit 4.0 Editor](https://developer.microsoft.com/en-us/windows/develop/multilingual-app-toolkit) (short "MAT", a tool build by Microsoft). The feedback that I get from my translators is that the tool it to complicated. It also has the big downside that it can't change the texts of the default/base language, so some manually translating still has to happen to the default language.

I've been looking at ResXResourceManager for a long time now. It has many benefits, we really like the simple interface. But the tool is mostly targeted to developers. 

My question is, are there any plans to make a stand-alone version that is **striped down to only the translation parts** (the functionality that translators need, people who are not developers)?

More concrete (as a start):
* Disable changing the "Key" column!
* Remove the "Delete selected rows" button.
* Remove the "Add new key" button.
* Remove the "Configuration" tab.
* Remove the "Language" tab.
* Remove the "Output" tab.

**Comment by tom-englert** [comment]
No plans yet. People usually seem to export Excel files that they sent to the translators.
In Excel you could easily lock the columns, rows or cells you don't want to be editable.

**Comment by jerone** [comment]
Thank you for your reply. Interesting; export to Excel. But then you miss the simplicity of sorting, searching, grouping and missing translations highlighting.

**Comment by tom-englert** [comment]
But usually that's more developer related tasks. Just filter all missing translations, export them to Excel and send it to the translator, so he can concentrate on the subject.

**Comment by jerone** [comment]
And it also saves us from zipping and sending all the resx files. Ok, I'm convinced Excel is the best option.

What do you think about reformulating this issue to adding an option for lock the untranslatable columns in the Excel export (project, file, key, etc...)?

**Comment by tom-englert** [comment]
Good idea, this sounds reasonable. Please create a new issue for this.
