### ISSUE TITLE
Keys are added in first file

### ISSUE THREAD

**Issue by bisato** [tom-englert/ResXResourceManager#163]
When I add a new Key and only fill the translation in german, the key is also added in the first (in our case, the cs-CZ) file with empty value. Like this:
`  <data name="test" xml:space="preserve">
    <value></value>
  </data>`
See the attached sample.
[Resx.zip](https://github.com/tom-englert/ResXResourceManager/files/2286735/Resx.zip)

**Comment by tom-englert** [comment]
The governing file that holds all the keys, and that controls the code generation, is the neutral language file. 
However you don't have a neutral language file, so ResXManager just picks the first language.
