### ISSUE TITLE
Visual Studio 2017 hangs

### ISSUE THREAD

**Issue by TomVandevelde** [tom-englert/ResXResourceManager#170]
Hi, 

First of all, it's a very nice tool to manage my resx-based resources. Despite this when I open the extension, Visual Studio hangs, also when I put in a new filter.

Is it possible to take a look at it?

Thanks in advance.

Best regards, Tom.

**Comment by tom-englert** [comment]
"hangs" is not very specific..., hangs forever? Even with an empty solution?
Maybe you can add some more info.

**Comment by TomVandevelde** [comment]
Hi, sorry for my bad explanation. The extension freezes VS for a couple of seconds (max 30 sec) when you open the resx manager. If you open it with an empty solution, I do not notice the problem.
![capture](https://user-images.githubusercontent.com/8954986/45413883-81845980-b67a-11e8-8773-f1924990a48d.PNG)
![capture2](https://user-images.githubusercontent.com/8954986/45413884-81845980-b67a-11e8-8cfc-510922c6725f.PNG)

**Comment by tom-englert** [comment]
Sorry, ResXManager is not the only root cause here - to show the projects and the resources, it has to call some Visual Studio methods, which cause the main delay, because these calls have to be done on the main UI thread - so there is nothing much one can do about.
