### ISSUE TITLE
FEature Request

### ISSUE THREAD

**Issue by Pr1Smiley** [tom-englert/ResXResourceManager#173]
Would like to see a Spell Check that targets the Default or chosen Field

Excellent product!

**Comment by tom-englert** [comment]
Spell check should work for every language where you have a full language pack installed.

**Comment by Pr1Smiley** [comment]
Tom, how do you enable spell check , as i do not see any button, am i missing something?

**Comment by tom-englert** [comment]
Just added some instructions in the wiki:
https://github.com/tom-englert/ResXResourceManager/wiki/Spell-Checker

**Comment by tom-englert** [comment]
@Pr1Smiley did that answer your question?

**Comment by tom-englert** [comment]
@Pr1Smiley still alive?

**Comment by tom-englert** [comment]
no response - seems to be fixed
