### ISSUE TITLE
Question about using translation as key

### ISSUE THREAD

**Issue by jorismathijssen** [tom-englert/ResXResourceManager#175]
Hello, 

First of all this is a fantastic tool and thanks to all of the contributors!

I'm currently working with a .net core project and we use the original translation as key. Inside the language specific resx we add the translated value.

![image](https://user-images.githubusercontent.com/1663370/46090449-03af6a80-c1b1-11e8-9e23-d82fd7c5e6df.png)

according to Microsoft this is a correct way of using resx. But the manager keeps giving me warning. Is there a way to fix the warning?

**Comment by tom-englert** [comment]
ResXManager does not put any restrictions on the key, the screenshot above is from the VS build in resource editor.

**Comment by jorismathijssen** [comment]
Yes! Thank you!

**Comment by tom-englert** [comment]
Now that you found you have blamed the wrong tool, maybe think again about your rating? :smirk:
