### ISSUE TITLE
Missing column name for neutral language in Excel

### ISSUE THREAD

**Issue by jerone** [tom-englert/ResXResourceManager#178]
When exporting to Excel, the column name for the neutral language is empty.

ResXResourseManager showing the neutral language as:
![image](https://user-images.githubusercontent.com/55841/46282731-944fc700-c572-11e8-8e00-277466e6a38e.png)

Excel not showing the neutral language (see column E, row 1):
![image](https://user-images.githubusercontent.com/55841/46282725-90bc4000-c572-11e8-92f4-6b293456dea2.png)

I expected to see in E1 the column name "Neutral (Dutch)" or at least "Default language", instead of empty cell.

**Comment by jerone** [comment]
You mean that ResXResourceMananger requires that cell E1 needs to be empty?

**Comment by tom-englert** [comment]
Yes, during import an empty field is the "id" of the neutral language

**Comment by tom-englert** [comment]
Closed, this is by design and is hard to change
