### ISSUE TITLE
Suggestion: Secondary languages as nested entries (DependentUpon)

### ISSUE THREAD

**Issue by chvogel** [tom-englert/ResXResourceManager#18]
Hi

First of all, thanks for creating an awesome extension for managing translations!
I keep wondering why there are so few good localization tools out there and even the good ones usually lack one feature or the other. However, with your extension, I am very happy so far.

There is one (hopefully small) feature request I have:
Would it be possible to create/update secondary .resx files with the `<DependentUpon>` tag so that they show up as sub-items to the neutral language .resx file?
I do this for all my .resx files manually and it helps a lot with keeping the solution nicely structured instead of having many similar files that are rarely edited clutter up the view.
It could be added as an optional feature that can be enabled in the configuration, maybe even with a button to update all existing .resx files in the same manner (same as with the "Sort all files now" button).

The resulting view in the Solution Explorer would be like this:
```
+ Solution
  + Project
    - FileA.cs
    + ResourceA.resx
      - ResourceA.de.resx
      - ResourceA.fr.resx
```

**Comment by tom-englert** [comment]
Wouldn't this be rather a task for https://github.com/madskristensen/FileNesting? 
Maybe this can be already done with the right naming convention?

**Comment by chvogel** [comment]
I checked out the FileNesting extension you mentioned and while it offers a nice UI to manually change nesting, there's absolutely no documentation about how automatic nesting is supposed to work and how to define rules for automatic nesting.

As for the "correct" folder layout: As so often, there's probably five different opinions if you ask five different devs.
Personally, I strongly favor file/folder structures where related components are as close together and as isolated from the rest as possible. Therefore, it seems logical to me to place the neutral language .resx and all localized .resx files in the same folder and simply group them together visually in VS, since they all belong to the same thing (the localized resource dictionary). VS also does it the same way with .Designer.cs files and WinForms per-form .resx files.

I have evaluated a commercial "localization helper" software named Infralution Globalizer which offers this kind of automatic nesting of localized .resx files. It offers a number of other features as well, some of which also exist in your extension which is why I would favor your extension for smaller projects or hobby projects where there's not really a budget for a special localization software.

**Comment by tom-englert** [comment]
I never said this is not "correct", just pointed out that there are other solutions that work out of the box :smirk: 

It looks like a cool feature, so if you think it's worth the effort maybe you can provide a PR for it? However I had a look at the source of https://github.com/madskristensen/FileNesting, and it looks it would be much easier to add the feature there.

**Comment by tom-englert** [comment]
@chvogel you can vote for that feature request in the FileNesting project to push it...

**Comment by tom-englert** [comment]
@chvogel you can try the CI build of FileNesting with the new feature at https://ci.appveyor.com/project/madskristensen/filenesting/build/1.0.76

**Comment by tom-englert** [comment]
Solved by https://github.com/madskristensen/FileNesting
