### ISSUE TITLE
When columns are filtered out they will still be copied

### ISSUE THREAD

**Issue by StefanJanssen95** [tom-englert/ResXResourceManager#180]
Copying while columns are hidden their data is still copied.

**How to reproduce:**
1. Deselect some columns
2. Press the rectangle in the top-left to select everything
3. Copy by either ``CTRL``+``C`` or the Copy button on the UI.
4. Go to Excel (or probably any other tool you could copy the data to)
5. All columns are shown, even the ones that were not selected.

**Expected:**
Only shown columns are copied

**System:**
Windows 10 Pro 10.0.17763 build 17763

**Comment by tom-englert** [comment]
I have improved this. However the above only applies when cell-selection is active: 
![image](https://user-images.githubusercontent.com/10229954/46804970-400fc880-cd64-11e8-931c-165b186b3d2a.png)
In the default row-selection mode always the whole row is copied, regardless of the visible columns.
