### ISSUE TITLE
The ResXManager window cannot be opened, a null reference exception is thrown. (ResXManager 1.26.1287 on Visual Studio 15.8.8)

### ISSUE THREAD

**Issue by treaschf** [tom-englert/ResXResourceManager#184]
I have ResXManager as a tool window in Visual Studio 15.8.8, auto-hidden. I cannot open it anymore. I uninstalled and then reinstalled ResXManager, but the problem still persists. I cannot open its window from the Tools menu either.

When Visual Studio crashed from this, I chose to debug it, and I'm attaching a print screen of what I've found.

![resxmanager](https://user-images.githubusercontent.com/44566067/47635973-79677700-db5f-11e8-9d6e-5f862865458e.png)

**Comment by tom-englert** [comment]
and did you try https://github.com/remcoros/DuplicateExtensionFinder?

**Comment by treaschf** [comment]
The DuplicateExtensionFinder has found no duplicates. When I click the ResX Manager from the Tools menu, my Visual Studio stops responding for a few seconds, and then I get this:

![resxmanager2](https://user-images.githubusercontent.com/44566067/47698495-4339fe00-dc18-11e8-9389-516c6b06eaeb.png)

The output window in the debugger has no useful information in it:

![resxmanager3](https://user-images.githubusercontent.com/44566067/47698778-526d7b80-dc19-11e8-9fb7-755430bc8bd4.png)

**Comment by tom-englert** [comment]
can you try the latest build:
http://vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a/

**Comment by treaschf** [comment]
It works. Thank you. :)
