### ISSUE TITLE
Add the Deepl translation engine to the list of supported engines

### ISSUE THREAD

**Issue by klacol** [tom-englert/ResXResourceManager#191]
I have an API key for Deepl. It would be nice, to be able to use it in the ResXResourceManager.

Deepl has a simple REST API: https://www.deepl.com/api.html

Would it be possible to integrate it? What would have to be done?

**Comment by tom-englert** [comment]
You just have to add another translator into https://github.com/tom-englert/ResXResourceManager/tree/master/ResXManager.Translators, using one of the existing as a template.

**Comment by klacol** [comment]
I have added the file DeeplTranslator.cs to the Translators project. I get the answers from Deepl, but I can't figure out, how to return the results. Has something to do with this, I assume:
 
`translationSession.Dispatcher.BeginInvoke`

**Comment by tom-englert** [comment]
I'm not sure what you mean by this? Having a quick look at the code I can't find anything wrong.

What happens when you debug this? Do you have more than one translator active? Maybe it's just hidden among the other results?

**Comment by tom-englert** [comment]
Fixed by #309
