### ISSUE TITLE
Support for Visual Studio 2019 Preview

### ISSUE THREAD

**Issue by db71** [tom-englert/ResXResourceManager#196]
Since today (04-12-2018) Visual Studio 2019 Preview is released. I would likt to see ResXResourceManager support for VS2019.

Thanks!

**Comment by db71** [comment]
This is what the VSIX installer shows when trying the latest build of the extension:

![image](https://user-images.githubusercontent.com/14137117/49469750-a109c900-f808-11e8-8731-d1146bd533e3.png)

**Comment by tom-englert** [comment]
That should be fixed, can you try again?

**Comment by pertraindev** [comment]
Thank you. It is working now but VS throws a warning at the top.

![warning](https://user-images.githubusercontent.com/38306427/49555430-9146cd80-f94b-11e8-9896-8ba2765c7f3e.png)

Thought you might want to know.
