### ISSUE TITLE
Always on top off?

### ISSUE THREAD

**Issue by Ruud-cb** [tom-englert/ResXResourceManager#197]
In a quick search I could not find any related issue so I would just like to ask: Could you make it possible to change the current behavior of the ResxResourceManager (within Visual Studio) so that it doesn't stay on top?

Just like I would pull out a tab from all of my code files: They end up in the background when some other window goes on top of it, like visual studio itself.

Of course the short answer could be: Just close it? but I am just used to alt-tabbing to other windows. ResxResourceManager is one of those windows that you need throughout the entire day, but don't really want to have it up in your face all the time.

Would be appreciated!

**Comment by tom-englert** [comment]
@Ruud-cb unfortunately I have no control over the way VS handles tool windows - ResxManager provides only the content, the frame is controlled by VS...

**Comment by tom-englert** [comment]
@Ruud-cb just found this property after upgrading the dependencies:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.providetoolwindowattribute.documentliketool?view=visualstudiosdk-2017
Maybe this is what you are looking for?

**Comment by Ruud-cb** [comment]
Thanks!

**Comment by tom-englert** [comment]
@Ruud-cb this is not build in yet! You can investigate, if this works and provides the behavior you wanted, and provide a PR if it's an improvement.

**Comment by Ruud-cb** [comment]
Ah oke, I could take a look soon. But the question is if we want to behave it like this by default if it works as desired?

**Comment by tom-englert** [comment]
Not sure, I would need to see it working first and try it out.
I usually have the window just docked with the documents, so it's automatically hidden when I don't use it.
