### ISSUE TITLE
Found the reason for someone reporting Exception in Code Reference part..

### ISSUE THREAD

**Issue by mwedmark** [tom-englert/ResXResourceManager#198]
In file: CodeReferenceTracker.cs on about line 215 (I've split that line in 2 lines here for debug purpose):

```
var matchGroup = match.Groups.Cast<Group>().Skip(1).Where(group => group?.Success == true);
foreach (var group in matchGroup)
```

What is the reason to do Skip(1)? Is it to remove the original anonymous group match from the ($Key) replacement? If so, sometimes that first one is the correct match and the second one can become that anonymous group match that should have bben removed. Then that line makes the rest of the code crash with "Invalid parameter Exception: length". 

Lets see if this is good enough input to fix problem. I will try and fix it and, if needed, I can send you files that crash after some "washing" of data from them.

**Comment by tom-englert** [comment]
Never heard about such a crash.
Closed because there was no more feedback.
