### ISSUE TITLE
Crashes often when opening the manager

### ISSUE THREAD

**Issue by Solethia** [tom-englert/ResXResourceManager#20]
When we open the manger is often crashes VS2017. This also happens when we search with the checkmark on. We have one solution with several thousand keys, in around one hundred different resource files with four languages(for now). It would be nice with a setting that set it to default not have the 'search checkmark' checked when opening the manager.

**Comment by tom-englert** [comment]
If VS crashes, it would be great to have a crash dump and a description of the kind of crash (just not responding, dr. Watson, just closing?) and then send this to MS.

I assume with 'search checkmark' you are referring to the selection of all resource files in the left hand list box. That does not make a real difference, since the data grid is virtualizing, so the performance factor is just the size of the window and the number of visible items.

My test set is 15.000 entries in 29 languages, and selecting all takes just some 100ms.

Usually the bottleneck is Visual Studio itself, because enumerating all items in the solution may take some time, but this happens no matter if there is anything selected or not.

With VS2017 you may use lightweight solution load, and have only the projects you are interested in loaded - this will reduce the number of active solution items to enumerate.

**Comment by tom-englert** [comment]
P.S. Can you select "Show performance tracer messages in output window" and see where it spends the most time?

**Comment by tom-englert** [comment]
@Solethia any chance to get the performance tracer messages?

**Comment by Solethia** [comment]
I'll see if I can get it done by tomorrow.

**Comment by Solethia** [comment]
Heres a trace of me adding a new key and populating it.

DTE event: Solution opened
>>> 1: ResourceManager.Load @15:29:49.8
>>> 2: Enumerate source files @15:29:49.8
<<< 2: Enumerate source files 00:00:01.7514745
<<< 1: ResourceManager.Load 00:00:03.1540429
>>> 3: Enumerate source files @15:29:55.7
<<< 3: Enumerate source files 00:00:01.5966666
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: C:\Users\dmpe\AppData\Local\Microsoft\VisualStudio\15.0_43de6f44\Extensions\rtxkndga.1zg
Version: 1.1.424.0
>>> 4: ResourceManager.Load @15:32:38.8
>>> 5: Enumerate source files @15:32:38.8
<<< 5: Enumerate source files 00:00:01.3377033
<<< 4: ResourceManager.Load 00:00:02.3836231
>>> 6: Enumerate source files @15:32:41.2
<<< 6: Enumerate source files 00:00:01.2975704
>>> 7: ListBox.SelectAll @15:32:42.6
<<< 7: ListBox.SelectAll 00:01:09.4564170
>>> 8: ListBox.SelectAll @15:34:15.2
<<< 8: ListBox.SelectAll 00:00:00.0806845
>>> 9: ListBox.SelectAll @15:34:53.7
>>> 10: Enumerate source files @15:34:53.8
<<< 10: Enumerate source files 00:00:01.3391297
<<< 9: ListBox.SelectAll 00:00:01.4140374
>>> 11: ListBox.SelectAll @15:36:12.7
<<< 11: ListBox.SelectAll 00:00:00.0996503
DTE event: Document opened
DTE event: Document opened
DTE event: Document opened
>>> 12: ResourceManager.Load @15:39:11.0
>>> 13: Enumerate source files @15:39:11.0
<<< 13: Enumerate source files 00:00:02.0379471
<<< 12: ResourceManager.Load 00:00:03.8721788
>>> 14: Enumerate source files @15:39:18.1
<<< 14: Enumerate source files 00:00:01.3727310
>>> 15: ResourceManager.Load @15:39:49.7
>>> 16: Enumerate source files @15:39:49.7
<<< 16: Enumerate source files 00:00:01.3918256
<<< 15: ResourceManager.Load 00:00:02.5183229
>>> 17: Enumerate source files @15:39:52.2
<<< 17: Enumerate source files 00:00:01.3323462
>>> 18: Enumerate source files @15:40:17.0
<<< 18: Enumerate source files 00:00:01.4058756

**Comment by tom-englert** [comment]
- I wonder why there are so many load events - do you open the resources in other editors, too?
- Taking one minute to populate the grid is quite unusual - are you low on memory, so that the system starts swapping?
- Can you try to open the solution with the standalone version - does it have the same performance issues?

**Comment by Solethia** [comment]
@tom-englert Sorry for the delay.

In this instance I only had _one_ ResX Resource Manager window open and a few .cs files (2-5). I've never used more than one window.

Heres some memory information:
![image](https://user-images.githubusercontent.com/5747583/28157119-c1a64b8c-67b5-11e7-9ae4-9cf18bd90743.png)

The standalone version is a lot faster. Here is a trace of me adding a key and populating it with the standalone (Same operation as before):

10:31	Started
10:31	ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
10:31	Assembly location: C:\Users\dmpe\AppData\Local\Apps\2.0\0JR6ZPT9.QR6\L3VK4AYQ.LM1\resx..tion_bef27c8ddc222f28_0001.0002_de2f5fa315436994
10:31	Version: 1.2.439.0
10:31	>>> 1: ResourceManager.Load @10:31:17.2
10:31	<<< 1: ResourceManager.Load 00:00:03.3499236
10:31	>>> 2: ListBox.SelectAll @10:31:23.0
10:31	<<< 2: ListBox.SelectAll 00:00:01.0156464
10:31	>>> 3: ListBox.SelectAll @10:31:26.5
10:31	<<< 3: ListBox.SelectAll 00:00:00.0179850
10:32	>>> 4: ListBox.SelectAll @10:32:07.1
10:32	<<< 4: ListBox.SelectAll 00:00:02.2091250
10:40	>>> 5: ListBox.SelectAll @10:40:14.6
10:40	<<< 5: ListBox.SelectAll 00:00:00.0465169

**Comment by tom-englert** [comment]
I see, not saving changes on edit immediately is the reason for the DocumentOpen events.

Since both standalone and VS extension share exactly the same code base for the views, I have no idea why populating the view in VS takes so much longer. I never experienced this.

**Comment by Solethia** [comment]
The recent update fixed this issue.
