### ISSUE TITLE
after installing visual studio 2017 15.9.2 , resxresourcemanager open a BLANK window.

### ISSUE THREAD

**Issue by taula50** [tom-englert/ResXResourceManager#200]
After updating to last version of visual studio 2017 community(15.9.2), when i try to open ResXResourceManager, only opens a blank window.

**Comment by tom-englert** [comment]
Please provide a proper issue description, including output messages.

**Comment by taula50** [comment]
there is no messages  when you right-click over a form and chose rexrseourcemannager, it opens a blank window, nothing  else, when it opened the normal window with a grid and texts for all the languages we added resources for..

**Comment by jsaf80** [comment]
I had the same Issue. Look at that link:

https://github.com/tom-englert/ResXResourceManager/wiki/Fixing-errors

**Comment by taula50** [comment]
Thanks **jsaf80**, but still blank window. I dont have any advice, so i decide to run DuplicateExtensionsFinder. exe and it says NO DUPLICATES FOUND.  I have windows 10 with last updates, and x86. using  target CPU x86 and framework 4.6.1.

**Comment by taula50** [comment]
Got it to work!. after uninstalled Bundler & Minifier,  ResXResourceManager  works!!

**Comment by marcelbeeker** [comment]
Installed version 1.15 (very old). It's working now! So the problem has to deal with the newer versions of the Resxmanager

**Comment by tom-englert** [comment]
Just read the output:
```
Assembly 'System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' loaded from file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/IDE/PrivateAssemblies/System.Windows.Interactivity.DLL
Assembly 'System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' loaded from file:///c:/users/marcelb/appdata/local/microsoft/visualstudio/15.0_81dad050/extensions/wctis5sm.eiw/System.Windows.Interactivity.dll


Duplicate assemblies found: 
System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, 
System.IO.FileSystem, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, 
System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

Please read https://github.com/tom-englert/ResXResourceManager/wiki/Fixing-errors before creating an issue.
```

**Comment by DaniilPalii** [comment]
> Got it to work!. after uninstalled Bundler & Minifier, ResXResourceManager works!!

After uninstalled Bundler & Minifier, I still have empty window. How do You find extension that need to be uninstalled?

**Comment by tom-englert** [comment]
@DaniilPalii just look at the output and follow the instructions...

**Comment by marcelbeeker** [comment]
I read this my problem is not mentioned in your solutions...

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by impoetk** [comment]
@tom-englert in my case i have vs 15.9.4, was previously using version 1.30 of your extension, and was working fine, it showed me all resources like normal, but i got a notification that the extension was updated, after restarting visual studio 1.32 version was installed and now resx manager window is empty

**Comment by DaniilPalii** [comment]
> @DaniilPalii the output ends with
> Please read https://github.com/tom-englert/ResXResourceManager/wiki/Fixing-errors before creating an issue.

Of course I read this article before asking and still don't understand what should I delete. I try remove duplicates with https://github.com/remcoros/DuplicateExtensionFinder but still have same problem. Maybe easier will be downgrade to previous version as @impoetk suggest? Is it possible?

**Comment by jsaf80** [comment]
Look in the whole output for 31bf3856ad364e35 and delete the one in the programfolder.

**Comment by tom-englert** [comment]
@DaniilPalii just delete the `System.Windows.Interactivity.dll` from `C:/Program Files (x86)/Microsoft Visual Studio/2017//Common7/IDE/PrivateAssemblies`, as described in the wiki.

**Comment by DaniilPalii** [comment]
> @DaniilPalii just delete the `System.Windows.Interactivity.dll` from `C:/Program Files (x86)/Microsoft Visual Studio/2017//Common7/IDE/PrivateAssemblies`, as described in the wiki.

I don't have `System.Windows.Interactivity.dll` in `PrivateAssemblies` than I tried to delete `System.IO.FileSystem.dll` and `System.Xml.ReaderWriter`. Without `System.IO.FileSystem.dll` VS crashed at start. Without `System.Xml.ReaderWriter` VS still works but ResX Manager give another output: `Duplicate assemblies found: System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, System.IO.FileSystem, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, System.IO.FileSystem.Primitives, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, System.Security.Cryptography.Primitives, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`. Without any of those dll files VS cannot start.

**Comment by tom-englert** [comment]
@DaniilPalii Since you never posted the relevant part of the log, this was just a guess. 

I just released a new version, maybe that also fixes your issue.

**Comment by DaniilPalii** [comment]
> @DaniilPalii Since you never posted the relevant part of the log, this was just a guess.
> 
> I just released a new version, maybe that also fixes your issue.

Works! You are the best, thank You!

**Comment by marcelbeeker** [comment]
@tom-englert/ResXResourceManager<mailto:reply@reply.github.com>

Your update solves my problem too!

You are great!

Thanks

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: DaniilPalii <notifications@github.com>
Verzonden: Saturday, January 5, 2019 2:41:37 PM
Aan: tom-englert/ResXResourceManager
CC: marcelbeeker; Mention
Onderwerp: Re: [tom-englert/ResXResourceManager] after installing visual studio 2017 15.9.2 , resxresourcemanager open a BLANK window. (#200)


@DaniilPalii<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDaniilPalii&data=02%7C01%7C%7C39b74c3e0aa2436a083508d6731384e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636822924994879197&sdata=tivXdaWCSkAHo0EWau7PJijNV9R4HS37BaSn%2F8%2BESGE%3D&reserved=0> Since you never posted the relevant part of the log, this was just a guess.

I just released a new version, maybe that also fixes your issue.

Works! You are the best, thank You!
