### ISSUE TITLE
Empty trailing header columns raises exception

### ISSUE THREAD

**Issue by TommyDuc** [tom-englert/ResXResourceManager#203]
We had a problem where the user probably deleted the two last languages in the Excel file, but Excel still considered them to exist, this could be seen by doing a Ctrl+A in the Excel file where the two last columns were selected even if they were empty. This was also confirmed by exporting to CSV.

Attempting to load this Excel file would raise an exception with the message "Duplicate language in header". It took us a few hours to figure out that the solution was to delete those two columns in Excel.

IMO, the tool should discard empty trailing columns, or at least give a more detailed exception message when this particular condition happens.

![image](https://user-images.githubusercontent.com/27635721/53030398-b5895500-3438-11e9-965f-2e3c862f4cc9.png)

**Comment by tom-englert** [comment]
@TommyDuc an empty cell in the header row denotes the neutral culture - so this sheet appears to have three columns for the neutral language, that's what the message says.

Any suggestions for a better message?

**Comment by TommyDuc** [comment]
@tom-englert  You are right, however those columns were entirely empty, in addition of the neutral culture at the beginning, which is why I said that "empty trailing columns" as opposed to empty header cells. The real problem is how Excel is still defining those columns in its xml without showing it explicitly to the user, but that's just how the world is.

I think that the error message should include the duplicate languages, inside quotes so neutral cultures are visible, and if the duplicates are only neutral languages then a different message should show, indicating that this is caused by this particular situation and how to proceed to fix the Excel file (select the whole columns, right click, delete).

**Comment by tom-englert** [comment]
If you want to provide a PR, here would be the best place to normalize the table:
https://github.com/tom-englert/ResXResourceManager/blob/af9cf8b627b4b55fd095ffbbb7b70313e13bc184/ResXManager.Model/ResourceEntityExtensions.cs#L210-L213

**Comment by TommyDuc** [comment]
@tom-englert  Ok I'll look into it
