### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by SnakeChord** [tom-englert/ResXResourceManager#206]
Hello, 
I need to add new languages and the language resx files don't exist so far. How can I achieve to duplicate the original resx attributes (build action, custom tool, custom tool namespace) to the new generated resx files. I need to take the attributes from default language file (without language extension).

Example:
The default language file:
CalendarModels.resx
-Build Action: Embedded resource
- custom tool: PublicResXFileCodeGenerator
- custom tool namespace: ModelResources

The new one that was created by ResXManager:
CalendarModels.de.resx
-Build Action: Content
- custom tool: Empty
- custom tool namespace: Empty

Is it possible to duplicate the resx attributes?

Thank you for answer.
Br. 
Tomáš

**Comment by tom-englert** [comment]
Custom tool and namespace must be empty for all specific languages, else you get the same code generated multiple times...
Build Actions is set to Embedded resource by VS automatically.

**Comment by SnakeChord** [comment]
When I add a new resource file in App_LocalResources folder the build action is set to Content.
There is the source Build action in App_LocalResources folder set to Embedded and the output from the ResXManager is set to Compile.
Any ideas?

**Comment by tom-englert** [comment]
No, I never had such a problem. What kind of project is this?

**Comment by SnakeChord** [comment]
In this case it is Asp.Net web - mvc
I have one folder App_GlobalResources in root project - the new file in this folder was generated right.
Another Folder is in Views/Shared/App_LocalResources - here are files that was generated bad.

Here are some images:
The generated file.
![first](https://user-images.githubusercontent.com/2528248/53750394-f0b06d00-3ea9-11e9-8184-e22b43fd31dc.png)
The source resource file.
![second](https://user-images.githubusercontent.com/2528248/53750395-f1490380-3ea9-11e9-9bbd-219239e5fa60.png)

**Comment by tom-englert** [comment]
Is this an old style or SDK style project?
Is the behavior the same if you manually add the existing .resx files to the project?

**Comment by SnakeChord** [comment]
It is asp.net web mvc project with .net framework, the project was created 5 years ago.
Yes if I add resource file manually it is some like on the first image.
