### ISSUE TITLE
@Invariant Exception

### ISSUE THREAD

**Issue by bisato** [tom-englert/ResXResourceManager#209]
Hello,

when I define a entry as invariant by right-clicking it, I get a System.ArgumentException. See https://imgur.com/a/5Aesqv8
This can be reproduced on 1.34.1869.0

**Comment by tom-englert** [comment]
I can't reproduce this. 
The error says that you clicked on an undefined language - how/where did you click?

**Comment by bisato** [comment]
I right-clicked the key. Is our configuration wrong? We have multiple files with multiple languages each.
See: https://imgur.com/a/LLqfLGz

**Comment by tom-englert** [comment]
Looks like you don't have any neutral language files

**Comment by bisato** [comment]
I was expecting that. I am really sorry. Thank you for your help.
