### ISSUE TITLE
When opening ResXManager for specific resx it loads all Keys

### ISSUE THREAD

**Issue by Solethia** [tom-englert/ResXResourceManager#21]
~~When right clicking a .resx file it opens the manager and loads all keys, then filter to the specific .resx scope afterwards. This takes considerable time when your solution has around 15.000 keys. Wouldn't it be more efficient to defer loading of all keys untill you search?~~

Edit:
What I am suggesting is that if you open the ResXmanger from the right click context menu of a ResX file, it doesn't try to load all keys in the **solution** and instead loads keys related to that **specific .resx file** (for all languages), to decrease loading time.

**Comment by tom-englert** [comment]
What exactly do you mean with search? Search for a term in the data grid?

**Comment by Solethia** [comment]
I've edited the issue to better reflect the issue, since it was not very well formulated.

**Comment by tom-englert** [comment]
And how would you then get access to the other keys?

**Comment by Solethia** [comment]
I would have "Tools -> Open Resx Manager" always open with all keys.

# Option 1
Create it so you can activate it in configuration with a bool: 'Only load keys for .resx file in right click context menu'. Then you'd have close the resx manager and open it from Tools -> Open ResX Manager to get all keys explicitly.

# Option 2
Make an extra right click option:
Right Click (.resx) context menu -> Open in Resx Manager
Right Click (.resx) context menu -> Open in Resx Manager (Scoped)

Where the scoped version would only load as explained. 
**Optional**: when in a scoped 'mode' you could have a reload button.
**Optional**: Load all the .resx file names aswell and lazy load them.
**Optional**: Load all keys as soon as you search in the main search field.

My issue with this might also stem from the issue with slow loading / crashes in the other issue. Also I might have a different workflow compared to you and others, but usually I only need to work with one specific resource at a time.

**Comment by tom-englert** [comment]
Maybe this can solve your problem:

- Start VS
- Open ResXManager
- Uncheck the "select all" check box on the top left
- Open the solution

Now the grid should be empty after loading the solution, and you can select one specific file with a right click on the .resx in the solution explorer.

**Comment by tom-englert** [comment]
@Solethia Can you try the latest version, it now remembers if "select all" was active, and avoids some round trips when opening one resource from the solution explorers context menu.

**Comment by Solethia** [comment]
The recent update fixes this issue.
