### ISSUE TITLE
Exception on solution load crashing Visaul Studio

### ISSUE THREAD

**Issue by geskill** [tom-englert/ResXResourceManager#210]
Having ResX installed on studio 2017 first and later for RC of 2019. After ~2 weeks of this setup i got today an exception opening the solution in 2017. I disabled the extension - did not help. Deleted the .vs folder - did not help.
Opening a solution in 2019 worked fine. For 2017 it crashed for opening any solution no matter if it has *.resx files or not.

**Exception:**
> Anwendung: devenv.exe
> Frameworkversion: v4.0.30319
> Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
> Ausnahmeinformationen: System.ComponentModel.Composition.ImportCardinalityMismatchException
>    bei System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(System.ComponentModel.Composition.Primitives.ImportDefinition, System.ComponentModel.Composition.Hosting.AtomicComposition)
>    bei System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore(System.Type, System.Type, System.String, System.ComponentModel.Composition.Primitives.ImportCardinality)
>    bei System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValueCore[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, System.ComponentModel.Composition.Primitives.ImportCardinality)
>    bei tomenglertde.ResXManager.VSIX.VSPackage.<ReloadSolution>_Throttle_Fody_Method()
>    bei TomsToolbox.Desktop.DispatcherThrottle.<Tick>b__6_0()
>    bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
>    bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
>    bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    bei MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
>    bei System.Windows.Threading.DispatcherOperation.Invoke()
>    bei System.Windows.Threading.Dispatcher.ProcessQueue()
>    bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    bei MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
>    bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Workaround:**
Deinstall extension in blank studio and reinstall.

My best guess is that the extension has an issue of the side by side installation by sharing same setting config somewhere (duplicate entries).

**Comment by tom-englert** [comment]
This rather looks like a problem with the VSIX-installer, it sometimes messes up the installation, leaving duplicates behind.
Since re-installation already fixed it, there is nothing much that the extension can do to avoid it.
