### ISSUE TITLE
Visual Studio stopped responding

### ISSUE THREAD

**Issue by PhilPJL** [tom-englert/ResXResourceManager#213]
![image](https://user-images.githubusercontent.com/271656/55427340-a987cb80-557e-11e9-9543-a0eee5e8b6db.png)

We've been getting this in VS 2019 preview for a while.  It's still present in the release version.  We have a large-ish solution, 200 projects.

**Comment by tolkushkin** [comment]
Same message in Visual Studio 2019, but i have only ten projects in solution.

**Comment by tom-englert** [comment]
This message was introcuded by Microsoft to blame the extensions for the poor performance of VS.
This 6 seconds are spend inside VS, when ResXManager requests to save the first item.
There is nothing ResXManager could do about it.

**Comment by taublast** [comment]
You sure other extensions are not affecting this making ResX manager to be wait for them? Like resharper and stuff..

**Comment by tom-englert** [comment]
@taublast that's also possible. 
Anyhow if someone can find a solution how to avoid this, I'm happy to integrate it...

**Comment by tolkushkin** [comment]
You can use new async api for plugins https://blog.devsense.com/2019/02/whats-great-about-vs2019

**Comment by tom-englert** [comment]
https://github.com/tom-englert/ResXResourceManager/blob/5cbdd653576fa7701c1a847d407d65c8e99ed3b1/ResXManager.VSIX/VSPackage.cs#L51
