### ISSUE TITLE
ResXManager deletes Designer class

### ISSUE THREAD

**Issue by feldi1014** [tom-englert/ResXResourceManager#214]
While editing the key's Visual Studio check-out and locked the designer class from SVN.
After that the designer class is missing. I can found them in the basket.
After restoring from basket we have to add the class into the project and also to SVN (renew).
Later on I detect a duplicate key at the restored class. So I think that the ResXManager tries to generate a new class-file while editing the keys.

**Comment by tom-englert** [comment]
The desinger class is auto-generated by VisualStudio, whenever you change the .resx file, no matter if you use ResXManager or the built-in resx editor.
