### ISSUE TITLE
Feature Request: Analyzer to provide warnings on CI builds

### ISSUE THREAD

**Issue by Thieum** [tom-englert/ResXResourceManager#218]
It would be nice to have Roslyn Analyzers that pops the same warnings that ResxManager does in Visual Studio:
![image](https://user-images.githubusercontent.com/944894/56373522-1f22a700-61cf-11e9-839e-836a8ab69380.png)

It would be easier to enforce translation by having those warnings pop on CI builds.

Those analyzers would be distributed through NuGet.

**Comment by tom-englert** [comment]
Roslyn analyzers don't run at ci-builds, they only run in the editor. Where would you think warnings should pop up?

If you are looking for something to run at CI-Builds, take a look at https://github.com/tom-englert/ResXResourceManager/wiki/Scripting

**Comment by Thieum** [comment]
@tom-englert Roslyn analyzers can warn on command line builds, when integrated as nuget packages:
https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019#nuget-package-versus-vsix-extension

_To have rules enforced at build time, including through the command line or as part of a continuous integration (CI) build, install the analyzers as a NuGet package. Analyzer warnings and errors don't show up in the build report if you install the analyzers as an extension._

But I'm not familiar enough with them to know if it's possible to generate the warnings of missing translation.

**Comment by tom-englert** [comment]
Anyhow there are analyzers for C# or VB, but resources are not part of the source code, so what would you analyze?

**Comment by Thieum** [comment]
True, if I understand well, this issue would make the information we need available at least in the roslyn workspace through the [project object](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.project?view=roslyn-dotnet): https://github.com/dotnet/roslyn/issues/7772

That's at least one show stopper. 

I don't know if the project is accessible in the analyzers if this issue gets adressed.

**Comment by tom-englert** [comment]
@Thieum also ResXManager does not analyze any compilation, it works purely on the .resx files.
