### ISSUE TITLE
Pressing 'ESC' key when editing value should revert changes [feature request]

### ISSUE THREAD

**Issue by pietchaki** [tom-englert/ResXResourceManager#219]
When editing a value or key, pressing the 'ESC' key saves the current edit, I think the expected result would be to cancel the edit and revert the edition.
This is specially annoying when I'm navigating through my solution's resx files and accidentally press some key. Then there's no way to undo the change and I need to revert manually by openning the resx file directly.

Also, CTRL+Z shortcut don't work while editing.

**Comment by tom-englert** [comment]
@pietchaki actually it behaves exactly like you requested - what exactly is your problem?

**Comment by tom-englert** [comment]
closed - no feedback
