### ISSUE TITLE
[feature request] Search by key 

### ISSUE THREAD

**Issue by pietchaki** [tom-englert/ResXResourceManager#220]
when handling large resx files/solutions, it's annoying to scroll to the desired key and edit it. being able to search for a key value would help doing this. Just scrolling to the matching row would be enough, but showing only the matches would be better.

**Comment by tom-englert** [comment]
Just use the column filter

**Comment by pietchaki** [comment]
I looked for it many many times, and never noticed there was an filter icon in the corner of each column...
