### ISSUE TITLE
Can this tool generate resx from cshtml?

### ISSUE THREAD

**Issue by burak-tarhanli** [tom-englert/ResXResourceManager#222]
I've cshtml (razor view) files (in an ASP.NET Web Pages website, not web application).  I thought i can generate resx files from cshtml files, but i couldn't find a function to do it. Is there a way to do it?

**Comment by tom-englert** [comment]
You can use "move to resource" from within cshtml files to extract strings into resource files

**Comment by burak-tarhanli** [comment]
Thank you for the answer. 
If I don't get it wrong, this feature belongs to the ReSharper, not ResXResourceManager. So, do I need to install ReSharper to use the "move to resource" function? Because I do not have ReSharper installed and I cannot see the standalone "move to resource" function in ResXResourceManager.

**Comment by tom-englert** [comment]
This is also a feature of ResXManager, just mark some text and right click...

**Comment by burak-tarhanli** [comment]
This is a great extension and thank you so much.
