### ISSUE TITLE
See changes since last translation

### ISSUE THREAD

**Issue by donnib** [tom-englert/ResXResourceManager#223]
Hi,
If we change the neutral text to something else, how can we see in ResXResourceManager if it has changes so translator can look at that text again ? Is there a way to do that ?

/donnib

**Comment by tom-englert** [comment]
You can use snapshots
https://github.com/tom-englert/ResXResourceManager/wiki/Snapshots

**Comment by tom-englert** [comment]
No response, so this seams to work
