### ISSUE TITLE
Export/Import from web project

### ISSUE THREAD

**Issue by ashke98** [tom-englert/ResXResourceManager#225]
1. Is it possible to make table gird and get export from resx file and show in my project?
2. If option 1 is possible, can we edit the table and make excel file and import it to resources?

I guess this 2 option is what  visual studio is missing them, but with this extension we can cover that.

**Comment by tom-englert** [comment]
https://github.com/tom-englert/ResXResourceManager/wiki/Copy,-Paste,-Export-and-Import
