### ISSUE TITLE
Hindi numeral in format specifier crashes Visual Studio

### ISSUE THREAD

**Issue by NickBettsRandom** [tom-englert/ResXResourceManager#227]
When there is string value containing a Hindi numeral in a format specifier (for example {१}) Visual Studio will crash if the 'Show only lines with warnings or changes' is selected. Occurs 100% of the time.

ResXManager version: 1.35.2376
Visual Studio 2017 version: 15.6.4

BTW I attempted to build ResXManager so I could track down this problem myself, but it failed to build with some errors I did not know to fix. I'm sure this is just my own ignorance, but I am wondering if there is any forum to get some help getting started with contributing to ResXManager?

**Comment by tom-englert** [comment]
@NickBettsRandom if you have problems building the solution you can just post this here...

**Comment by NickBettsRandom** [comment]
The errors I get are:
`Error		Assembly 'C:\Users\Nick\.nuget\packages\windowsapicodepack-core\1.1.1\lib\Microsoft.WindowsAPICodePack.dll' must be strong signed in order to be marked as a prerequisite.`
`Error		Assembly 'C:\Users\Nick\.nuget\packages\windowsapicodepack-shell\1.1.1\lib\Microsoft.WindowsAPICodePack.Shell.dll' must be strong signed in order to be marked as a prerequisite.`
`Error	CS0121	The call is ambiguous between the following methods or properties: 'Task.Run<TResult>(Func<TResult>, CancellationToken)' and 'Task.Run(Func<Task>, CancellationToken)'	ResXManager.VSIX	C:\Dev\External\ResXResourceManager\ResXManager.VSIX\VSPackage.cs	125	Active`
I can solve the last one with a cast, but I would assume that the fact that I am getting it means something is going wrong.

I also get the following warning 2037 times.
`Warning	CS8032	An instance of analyzer Microsoft.CodeQuality.Analyzers.QualityGuidelines.AvoidDuplicateElementInitialization cannot be created from C:\Users\Nick\.nuget\packages\microsoft.codequality.analyzers\2.9.2\analyzers\dotnet\cs\Microsoft.CodeQuality.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	ResXManager.Infrastructure	C:\Dev\External\ResXResourceManager\ResXManager.Infrastructure\CSC	1	Active`
It appears that the most resent version of Microsoft Code Analysis for Visual Studio 2017 is 2.6.0 so I'm wondering if all my problems are due to the fact that you are using Visual Stuido 2019. I'm only using Visual Studio 2017 version: 15.6.4.

If you can shed any light on these problems that would be great.

**Comment by tom-englert** [comment]
I just tried with VS 2017 and it still builds fine...
Maybe you don't have the latest .Net framework installed?
