### ISSUE TITLE
Unexpected character

### ISSUE THREAD

**Issue by haunguyen84** [tom-englert/ResXResourceManager#232]
When edit a resource of Unicode file like fr, it could have some unexpected changes like in the attached image
![image](https://user-images.githubusercontent.com/27505173/61926990-265f0b00-af9d-11e9-845b-45a3d9402730.png)

**Comment by tom-englert** [comment]
loos like it added the correct [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) - this is not really unexpected.
