### ISSUE TITLE
Main page blank

### ISSUE THREAD

**Issue by Azagh3l** [tom-englert/ResXResourceManager#235]
I got a blank main page when loading.
I updated .NET framework version and resX Manager to last version.
Possibly linked to #72 

> Error: System.NotImplementedException: Non implémenté (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
>    at EnvDTE.ProjectItem.Open(String ViewKind)
>    at tomenglertde.ResXManager.VSIX.DteProjectFile.InternalLoad() in C:\Agent\_work\20\s\ResXManager.VSIX\DteProjectFile.cs:line 65
>    at tomenglertde.ResXManager.Model.ProjectFile.Load() in C:\Agent\_work\20\s\ResXManager.Model\ProjectFile.cs:line 63
>    at tomenglertde.ResXManager.Model.ResourceLanguage..ctor(ResourceEntity container, CultureKey cultureKey, ProjectFile file) in C:\Agent\_work\20\s\ResXManager.Model\ResourceLanguage.cs:line 76
>    at tomenglertde.ResXManager.Model.ResourceEntity.<GetResourceLanguages>b__44_2(<>f__AnonymousType3`2 <>h__TransparentIdentifier0) in C:\Agent\_work\20\s\ResXManager.Model\ResourceEntity.cs:line 277
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    at tomenglertde.ResXManager.Model.ResourceEntity.GetResourceLanguages(IEnumerable`1 files) in C:\Agent\_work\20\s\ResXManager.Model\ResourceEntity.cs:line 279
>    at tomenglertde.ResXManager.Model.ResourceEntity..ctor(ResourceManager container, String projectName, String baseName, String directoryName, ICollection`1 files) in C:\Agent\_work\20\s\ResXManager.Model\ResourceEntity.cs:line 36
>    at tomenglertde.ResXManager.Model.ResourceManager.LoadEntities(IEnumerable`1 fileNamesByDirectory) in C:\Agent\_work\20\s\ResXManager.Model\ResourceManager.cs:line 208
>    at tomenglertde.ResXManager.Model.ResourceManager.InternalLoad(IEnumerable`1 resourceFilesByDirectory) in C:\Agent\_work\20\s\ResXManager.Model\ResourceManager.cs:line 154
>    at tomenglertde.ResXManager.Model.ResourceManager.Load(IList`1 allSourceFiles) in C:\Agent\_work\20\s\ResXManager.Model\ResourceManager.cs:line 63
>    at tomenglertde.ResXManager.Model.ResourceManager.Reload(IList`1 sourceFiles) in C:\Agent\_work\20\s\ResXManager.Model\ResourceManager.cs:line 128
>    at tomenglertde.ResXManager.View.Visuals.ResourceViewModel.Reload(Boolean forceFindCodeReferences) in C:\Agent\_work\20\s\ResXManager.View\Visuals\ResourceViewModel.cs:line 489
> ResX Resource Manager loaded.
> Home: https://github.com/tom-englert/ResXResourceManager
> Report issues: https://github.com/tom-englert/ResXResourceManager/issues
> Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
> Assembly location: c:\users\branty\appdata\local\microsoft\visualstudio\15.0_4f96dd39\extensions\kynv4qtr.i0v
> Version: 1.36.2504.0
> .NET Framework Version: 461814 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
> Switch.System.Windows.Baml2006.AppendLocalAssemblyVersionForSourceUri=False (https://github.com/Microsoft/dotnet/blob/master/releases/net472/dotnet472-changes.md#wpf)
> Error: System.NotImplementedException: Non implémenté (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
>    at EnvDTE.ProjectItem.Open(String ViewKind)
>    at tomenglertde.ResXManager.VSIX.DteProjectFile.InternalLoad() in C:\Agent\_work\20\s\ResXManager.VSIX\DteProjectFile.cs:line 65
>    at tomenglertde.ResXManager.Model.ProjectFile.Load() in C:\Agent\_work\20\s\ResXManager.Model\ProjectFile.cs:line 63
>    at tomenglertde.ResXManager.Model.ResourceLanguage..ctor(ResourceEntity container, CultureKey cultureKey, ProjectFile file) in C:\Agent\_work\20\s\ResXManager.Model\ResourceLanguage.cs:line 76
>    at tomenglertde.ResXManager.Model.ResourceEntity.<GetResourceLanguages>b__44_2(<>f__AnonymousType3`2 <>h__TransparentIdentifier0) in C:\Agent\_work\20\s\ResXManager.Model\ResourceEntity.cs:line 277
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    at tomenglertde.ResXManager.Model.ResourceEntity.GetResourceLanguages(IEnumerable`1 files) in C:\Agent\_work\20\s\ResXManager.Model\ResourceEntity.cs:line 279
>    at tomenglertde.ResXManager.Model.ResourceEntity..ctor(ResourceManager container, String projectName, String baseName, String directoryName, ICollection`1 files) in C:\Agent\_work\20\s\ResXManager.Model\ResourceEntity.cs:line 36
>    at tomenglertde.ResXManager.Model.ResourceManager.LoadEntities(IEnumerable`1 fileNamesByDirectory) in C:\Agent\_work\20\s\ResXManager.Model\ResourceManager.cs:line 208
>    at tomenglertde.ResXManager.Model.ResourceManager.InternalLoad(IEnumerable`1 resourceFilesByDirectory) in C:\Agent\_work\20\s\ResXManager.Model\ResourceManager.cs:line 154
>    at tomenglertde.ResXManager.Model.ResourceManager.Load(IList`1 allSourceFiles) in C:\Agent\_work\20\s\ResXManager.Model\ResourceManager.cs:line 63
>    at tomenglertde.ResXManager.Model.ResourceManager.Reload(IList`1 sourceFiles) in C:\Agent\_work\20\s\ResXManager.Model\ResourceManager.cs:line 128
>    at tomenglertde.ResXManager.View.Visuals.ResourceViewModel.Reload(Boolean forceFindCodeReferences) in C:\Agent\_work\20\s\ResXManager.View\Visuals\ResourceViewModel.cs:line 489

**Comment by tom-englert** [comment]
If you look at the call stack you see that Visual Studio throws an exception when trying to load one of the items in one of your projects:
```
Error: System.NotImplementedException: Non implémenté (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
at EnvDTE.ProjectItem.Open(String ViewKind)
```
So looks like there is a corrupt project in your solution

**Comment by Azagh3l** [comment]
You're right, thanks !
