### ISSUE TITLE
Suggestions on View Layout

### ISSUE THREAD

**Issue by taoyouh** [tom-englert/ResXResourceManager#237]
The manager is powerful, but I think its UI can be better.

First, the main view has many objects not aligned with each other. For example:
![image](https://user-images.githubusercontent.com/11157438/63400258-bad65500-c405-11e9-8289-fa0040c71b3d.png)

Second, the top bar (including search bar and tool bar and the text box) can be resized now but it only affects the size of the text box (shown below). I suggest we should move that text box to the bottom of the data grid.
![image](https://user-images.githubusercontent.com/11157438/63400347-0b4db280-c406-11e9-85ff-c42a56687757.png)

**Comment by taoyouh** [comment]
In addition, many sizes are not multiples of 4px, which will cause many rounding problems in high DPI computers. For example, in a 150% scaled computer, 3px+3px in XAML will become 4.5px+4.5px on screen and be rounded into 5px+5px=10px, but 6px in XAML will become 9px on screen. I suggest we should change those 3px/5px to multiples of 4px.

**Comment by tom-englert** [comment]
The top bar just resembles the Excel layout, so it's clear to everyone what it's used for:
![image](https://user-images.githubusercontent.com/10229954/63422512-c6784a80-c40a-11e9-953a-ca29eaf72e58.png)

Feel free to provide a PR to fix the other things...

**Comment by tom-englert** [comment]
fixed via 69e2a8c
