### ISSUE TITLE
Error on Paste from Excel

### ISSUE THREAD

**Issue by miltoncamara** [tom-englert/ResXResourceManager#24]
Hello, I'm trying to paste the excel data but I'm getting the following error:

Error parsing the data from clipboard: The data you're pasting isn't the same size as your selection.

Is there any format so I can copy and paste?

Tks

**Comment by tom-englert** [comment]
I have improved the [wiki page](../wiki/Copy,-Paste,-Export-and-Import), maybe that helps resolving your issue.

**Comment by tom-englert** [comment]
@miltoncamara did that solve your problem?

**Comment by miltoncamara** [comment]
No! :( When I try to COPY and PASTE I receive the error above!

**Comment by tom-englert** [comment]
What mode are you using? What do you have selected in Excel, and what do you have selected in ResxManager?

**Comment by tom-englert** [comment]
@miltoncamara looks like you have found out how it works.

**Comment by miltoncamara** [comment]
Hello @tom-englert I'm sorry for the delay!

1 - I'm using the second mode, I'm copying all excel cells an then trying to paste in ResourceManager
2 - In excel I created same numbers of columns so ResourceManager.
3 - Is possible to copy all excel cells an then paste into Resource Manager?

Tk you so much

**Comment by tom-englert** [comment]
Yes, as long as the selection on both sides is the same (like copy/paste inside excel)

**Comment by miltoncamara** [comment]
@tom-englert I'll try again!
