### ISSUE TITLE
.Net Standard Class library resource issue

### ISSUE THREAD

**Issue by mldYM** [tom-englert/ResXResourceManager#240]
Adding a resource resx file to .net standard class library and right click on it dos't show "Open In ResXManager' , rebuilding project have no effect , by restating visual studio the ResXManager Is shown but adding a custom code generation with tt did't create T4 template for that resource and only create Solution Items\Resources.Designer.t4 , is there any workaround or can you fix this plz.
every things work ok if i use .net framework class libray 
Visual Studio 2019 16.2.4

**Comment by mldYM** [comment]
adding this to my csprj solve my problem , but i had add tt file myself

<ItemGroup>
    <None Update="**\*.Designer.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>$([System.String]::new('%(FullPath)').Replace('.tt', '')).cs</LastGenOutput>
      <DependentUpon>$([System.String]::new('%(FullPath)').Replace('.Designer.tt', '')).resx</DependentUpon>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <Compile Update="**\*.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>$([System.String]::new('%(FileName)').Replace('.cs', '')).tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.resx">
      <Generator></Generator>
      <LastGenOutput>$([System.String]::new('%(FileName)').Replace('.resx', '')).Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>


  <ItemGroup>
    <T4ParameterValues Include="SolutionDir">
      <Value>$(SolutionDir)</Value>
      <Visible>False</Visible>
    </T4ParameterValues>
    <T4ParameterValues Include="Configuration">
      <Value>$(Configuration)</Value>
      <Visible>False</Visible>
    </T4ParameterValues>
  </ItemGroup>

**Comment by tom-englert** [comment]
1. Context menu is visContext menu is visible after clicking the refresh button in ResXManager. Seems there are no more change events raised from Visual Studio for adding new items.

2. This is a bug in Visual Studio, see https://github.com/dotnet/project-system/issues/1870
What VS generates is this:
```xml
  <ItemGroup>
    <EmbeddedResource Update="Resource1.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <None Update="Resource1.Designer.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
  </ItemGroup>
```
What it should look like:
```xml
  <ItemGroup>
    <EmbeddedResource Update="Resource1.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <None Update="Resource1.Designer.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <DependentUpon>Resource1.resx</DependentUpon>
      <LastGenOutput>Resource1.Designer.cs</LastGenOutput>
    </None>
    <Compile Update="Resource1.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resource1.Designer.tt</DependentUpon>
    </Compile>
  </ItemGroup>
```
If you change your project by adding the dependencies, it should work again.

**Comment by mldYM** [comment]
thanks :)

i add that line to csproj and problem resolve 👍
