### ISSUE TITLE
No target languages available

### ISSUE THREAD

**Issue by NielsDWG** [tom-englert/ResXResourceManager#242]
Hi all,

As you can see in the image below, I am not able to select any target languages. In the main view everything seems correct as you can see on the second image.

Does anyone know what the problem could be?

I am using ResXManager 1.36.2407.0 and Visual Studio 2017 15.9.15

![image](https://user-images.githubusercontent.com/50589052/64604256-1d49c200-d3c2-11e9-9fe7-13ee35953aa0.png)

![image](https://user-images.githubusercontent.com/50589052/64604421-6863d500-d3c2-11e9-8042-f342bb783588.png)

**Comment by tom-englert** [comment]
Looks like you have added a new language, but not generated at least one resx file for that language.
Click into one of the French cells to create at least one empty entry.

**Comment by NielsDWG** [comment]
Thanks for your reply. It seems my problems are fixed now after I updated visual studio. For french, I had to add one entry, indeed.
