### ISSUE TITLE
Jetbrains Rider support

### ISSUE THREAD

**Issue by CleytonGoncalves** [tom-englert/ResXResourceManager#246]
Is there any plans for Rider support through a plugin, like the VS one? What would be the viability of it?

**Comment by tom-englert** [comment]
@matkoch I doubt Rider will support plugins with a WPF GUI, right?

However you can always use the standalone version: https://github.com/tom-englert/ResXResourceManager/releases/latest/download/Publish.zip

**Comment by CleytonGoncalves** [comment]
Just in case anyone else comes here looking for Rider support, now it has native support (as of 2020.2 EAP Build 202.5958.478).

```
Working with resources

The localization manager is now available in Rider. It allows you to view everything contained in .resx files in a single grid. You can also add, edit, rename, search for, and safely delete any localized resources, in addition to finding all resources that are missing localized values and hiding locales you don't need right now. You can access it using the Tools menu or by double-clicking on a .resx file.
```
https://web.archive.org/web/20200710152810/https://www.jetbrains.com/rider/nextversion/
