### ISSUE TITLE
How to force to re-calculate the index column values ?

### ISSUE THREAD

**Issue by GreatFireWall** [tom-englert/ResXResourceManager#248]
Now suppose I have 10 items, if I change the index from 7th to 4th, there're 2 4th index value items, this duplicate/wrong index will not be updated unless I add or delete an item.

**Comment by tom-englert** [comment]
The index has no meaning other than the sort order and will not be saved anywhere. After reloading the file from disk, they are unique again.
If you create duplicates, sort order within the dupes is random. To avoid duplicates, use fractional values, e.g. 3.5 instead of 4.

**Comment by GreatFireWall** [comment]
3.5 is a good idea, thanks.
