### ISSUE TITLE
Search specific text in Column

### ISSUE THREAD

**Issue by LudwinSt** [tom-englert/ResXResourceManager#249]
Hello,

I've been using this tool for translation. So in the Main tab I have the column for the source language (English) and in the column to the right the target language translation. There are some cases in which I need to translate concrete words, e.g., "Name", so as it is expected when I type "name" in the column filter, ResX RM shows me all text results that have the word "name" on it. This means sentences like "First Name" "A name must have 3 characters" and so on. What I need is to find texts that have the word "Name" and only that word. I tried used quotation marks, but it doesn't work. So I was wondering if there is any kind of filter I could use to find cells or text that only contain the specific text I'm searching. I don't know if this has been asked in the past, if so, apologies. I tried to read all threads and info related to this tool to see if I could find an answer before posting here, but with no luck.

Thanks

**Comment by tom-englert** [comment]
You can use regular expressions, e.g. ^name$

**Comment by LudwinSt** [comment]
Thanks, that's exactly what I needed.
