### ISSUE TITLE
Generated files wrong format dotnetcore

### ISSUE THREAD

**Issue by trikego** [tom-englert/ResXResourceManager#25]
Hi,

When I try to add a language in the resourcemanager the generated file has a wrong name.
let's say I have a folder Resource/Views/User
And it contains a resource file Index.nl.resx
If I add a language (eg. english) the generated file is: Index.nl.en.resx (and not Index.en.resx)

**Comment by tom-englert** [comment]
Seems you are missing the neutral resource - there should be an Index.resx as well.
In your scenario ResXManager assumes that Index.nl.resx is the neutral file, and Index.nl is the base name.

**Comment by trikego** [comment]
I followed the documentation from aspnet core:

If you create a resource file in Visual Studio without a culture in the file name (for example, Welcome.resx), Visual Studio will create a C# class with a property for each string. That's usually not what you want with ASP.NET Core; you typically don't have a default .resx resource file
[https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization](url)

But for now I will make a neutral file then. Thanks for the quick response!

**Comment by tom-englert** [comment]
You can remove the custom build step from the default resx file to omit the generation of the C# class.
