### ISSUE TITLE
Cannot configure Azure Endpoint

### ISSUE THREAD

**Issue by digitalsigi** [tom-englert/ResXResourceManager#252]
Thanks for this great tool! 
I'd like to use it with my Azure Account where I created a "Translate Text" resource.
I can easily get the API Key, but I also get an Endpoint which I should use together with the Key.
However, I did not find a way to configure the Endpoint in ResXManager.
Can one please advise how to do that?
Thx
Josef

**Comment by tom-englert** [comment]
You just don't need it

**Comment by digitalsigi** [comment]
Thx for caring. I got it working.
