### ISSUE TITLE
Google translate

### ISSUE THREAD

**Issue by pauloya** [tom-englert/ResXResourceManager#253]
I'm trying to get Google translate to work with my API key that I just created.
I get an empty translation from Google, and no indication of what the error could be.
At the bottom I only get "Google:" The Output tab is empty.
Can you help me diagnose the problem?

**Comment by tom-englert** [comment]
I don't have a Google account.
This was contributed by @dahall, maybe he can help you?

**Comment by pauloya** [comment]
I created a Pull Request that shows the 403 error I was getting with my API Key instead of an empty string.

**Comment by dahall** [comment]
I have reviewed the PR and believe it is a good addition.

**Comment by tom-englert** [comment]
Fixed by #254
