### ISSUE TITLE
Bug: selection of wrong .resx file when project contains custom controls

### ISSUE THREAD

**Issue by Hefaistos68** [tom-englert/ResXResourceManager#257]
When you add a custom control to your C# project, there is a .resx file for this control.
Now when you make a "Move to resource file" with any string in your code, the dialog will always select the custom controls .resx as target.

**Comment by tom-englert** [comment]
Seems you project file is missing some info. The parent item of the .resx file must have a `SubType` of either `Form` or `UserControl` to be properly detected as a control resource:

https://github.com/tom-englert/ResXResourceManager/blob/e693a7dbdfd509548bc3a75a97f133ff48919210/ResXManager.VSIX/DteProjectFile.cs#L149-L162

**Comment by Hefaistos68** [comment]
Understand. Well, its a standard VS 2019 created project and control, without manual modifications. Will keep an eye on this one.

**Comment by tom-englert** [comment]
Seems this is new in VS 2019, I will add "Component" to the list.
