### ISSUE TITLE
Standalone App ClickOnce - Security Warning

### ISSUE THREAD

**Issue by werddomain** [tom-englert/ResXResourceManager#258]
![Untitled](https://user-images.githubusercontent.com/7439269/69257885-c6aef000-0b89-11ea-9cda-257c42166e7b.png)

I have a standard configuration, no specific policy added to the system.

I wish to send this stand alone app to someone who will translate our ress, but he's unable to install it.
(We have found how to allow the app to install, this issue is only to let you know ;-) )

**Comment by tom-englert** [comment]
So how do you think this could be avoided?

**Comment by tom-englert** [comment]
This is a Windows issue
