### ISSUE TITLE
Inconsistent Build Warnings

### ISSUE THREAD

**Issue by Hefaistos68** [tom-englert/ResXResourceManager#259]
When building a rather large project, for a few items ResX gives me warnings for missing translations, all items that I see warned are header texts for multicolumn listviews. Nothing else shows up even as there are tons of missing translations.

**Comment by tom-englert** [comment]
Build warnings are limited to 20, so they don't impact build performance

**Comment by Hefaistos68** [comment]
Ok, understood. just maybe add warning #21 "further translation warnings suppressed" or something like that.
