### ISSUE TITLE
Imports .zh-CN into .ar-IQ

### ISSUE THREAD

**Issue by MarianXXL** [tom-englert/ResXResourceManager#26]
I've tried to import an Excel file with 49 Languages. The last two columns are .ar-IQ (empty) and .zh-IQ. The tool imports the .zh-IQ column into .ar-IQ and .zh-CN  resx file.   :-(

**Comment by MarianXXL** [comment]
I've tried to import an Excel file with 49 Languages. The last two columns are .ar-IQ (empty) and .zh-IQ. The tool imports the .zh-CN column into .ar-IQ and .zh-CN resx file. :-(

Sorry - the first description  was wrong

**Comment by tom-englert** [comment]
Sorry, I don't understand either of them, can you please add some more details? It would be very helpful to attach an Excel file that can reproduce the problem and some screenshots that show what happens.

P.S.: you can modify or delete your comments if you did wrong.

**Comment by MarianXXL** [comment]
[iCatcher_WEEDSCOUT_Translations.xlsx](https://github.com/tom-englert/ResXResourceManager/files/1151683/iCatcher_WEEDSCOUT_Translations.xlsx)

**Comment by MarianXXL** [comment]
Hi Tom,
I have in the project all resx file in the Project. Than I try to update them with the Excel file. All works fine, apart from the last two columns. The tool includes the last column .zh-CN into .ar-IQ resx file.

**Comment by tom-englert** [comment]
@MarianXXL with your sample .xlsx it was straight forward to reproduce. 
The CI build version on http://vsixgallery.com/ already has the fix.
