### ISSUE TITLE
Unable to import from Excel file correctly

### ISSUE THREAD

**Issue by bababbel** [tom-englert/ResXResourceManager#262]
I exported the translations from one branch and want to import it into another. They are not imported. When I try to clear a translation cell in ResXManager and import from Excel to fill it up again, it stays empty.
Since I export directly from ResXManager, the Excel File should be ok. I'm using VS 2017.

**Comment by tom-englert** [comment]
This is a rather vague description. Can you post a sample to reproduce this?

**Comment by tom-englert** [comment]
No feedback, closed
