### ISSUE TITLE
Improvement: allow adding file path in Excel export

### ISSUE THREAD

**Issue by EquipeGDO** [tom-englert/ResXResourceManager#263]
Our current workflow tends to use multiple RESX files in each project, often with a generic name (like "Resource.resx"). The files are in separate folders within that same project.
Would it be possible to add the path of the file within the Excel export?

**Comment by tom-englert** [comment]
It actually contains the path - so where is your problem?

![image](https://user-images.githubusercontent.com/10229954/69831163-73dbd500-1228-11ea-9991-59700b389d80.png)

**Comment by EquipeGDO** [comment]
That is strange, on my side I only get the filename, with no path leading to it.

![image](https://user-images.githubusercontent.com/58310240/69831983-d9649d00-11f9-11ea-98cf-5672a7222ec9.png)

To be clear, I am seeking the path to the file as it is visible by hovering the file in the interface, as such:

![image](https://user-images.githubusercontent.com/58310240/69832075-5a239900-11fa-11ea-8349-c773732e9689.png)

**Comment by tom-englert** [comment]
The path in the Excel is relative to the project, not the solution

**Comment by tom-englert** [comment]
BTW, how did you open your solution - I can't see the projects. It should rather look like this:

![image](https://user-images.githubusercontent.com/10229954/69856208-6573d480-128d-11ea-81dc-cf1fc1827a48.png)

**Comment by EquipeGDO** [comment]
All the of files in my previous screenshot were part of a single project.
Here's a less intense example of what I'm working with, part of the same solution:
![image](https://user-images.githubusercontent.com/58310240/69873966-d31d0200-1287-11ea-9a6d-b17178d94ad5.png)

All of this is legacy code over which I have little control, so modifying the files to have more unique names is not really an option.

This is what the solution looks like:
![image](https://user-images.githubusercontent.com/58310240/70063537-f44a5f00-15b5-11ea-8aa9-8801e2a436d5.png)

Here's what the most problematic project looks like in that structure:
![image](https://user-images.githubusercontent.com/58310240/70064666-e7c70600-15b7-11ea-92f7-3008874f89cb.png)

So while my initial request was for the file path, it is true that the path relative to project should suffice. I can't figure out why I'm not getting it on my side though.

**Comment by tom-englert** [comment]
I got no idea what's wrong with your projects, and I can't reproduce such a behavior.
`ApplicationComponents` looks like this is one project that imports lots of other projects. 
Can you post the project file?

**Comment by tom-englert** [comment]
@EquipeGDO can this be closed?

**Comment by EquipeGDO** [comment]
yes
