### ISSUE TITLE
Option Request: ignore ampersands 

### ISSUE THREAD

**Issue by Hefaistos68** [tom-englert/ResXResourceManager#270]
Button and other control texts often have ampersands in them for keyboard short cuts, they are not identical in different languages. I may have "&Add" in english but "A&dicionar" in portuguese. The leading/trailing punctuation doesnt catch that but reports it as warning.

**Comment by tom-englert** [comment]
Actually you can simply turn of punctuation checks for those lines (context menu)

**Comment by tom-englert** [comment]
In WPF the prefix is '_', not '&', so we need to handle both.
@mkaring any Idea how to improve this?

**Comment by Hefaistos68** [comment]
Sorry, no such option in my context menu. Only in the project configuration. Context menu only shows the cut/copy/paste, invariant and cell selection entries.

**Comment by mkaring** [comment]
The easiest way to ignore both the `_` and the `&` in the leading punctuation check. As far as I can tell `_` is used by WPF and `&` is used by everyone else.

The downside is that this may hide actual mistakes, as the mnemonic character is only used in specific cases. How ever those checks are mostly useful to spot missing characters that are easily overlooked. Single points and such. Both `_` and `&` are quite obvious characters.

Anything beyond this would require the resource to be identifiable as a string that may contain an mnemonic character and I don't think that is something you want to include, is it?

**Comment by Hefaistos68** [comment]
Maybe just include an aditional checkbox "Ignore & and _ " when punctuation checking is on?

**Comment by ImrePyhvel** [comment]
+1 to note that mnemonic characters is a specific sub case of translations. It would NOT be intuitive if `_` or `&` (or the next special characters) will be ignored.  

Genereally, making assumptions on translation content semantics can introduce feature creep and just cause overall confusion ("S&omeMenomonic" vs "R&D", etc). Any heuristic will miss exceptional cases and hence would bring requests for suppression feature to the suppression feature of the original warning.. It's a slippery slope.

IMHO current toolset is sufficient as user can suppress specific warnings for specific resources after explicit user review (including multi-selecting by chosen filter). It's simple and everything can be done.

**Comment by tom-englert** [comment]
@mkaring excluding '_' and '&' from the punctuation checks sounds a reasonable solution, without taking much value from the checks.

**Comment by Hefaistos68** [comment]
> Sorry, no such option in my context menu. Only in the project configuration. Context menu only shows the cut/copy/paste, invariant and cell selection entries.

Damn, now I understood why no context menu: the menu is only available when "Cell selection" is not activated. Somehow confusing. Might consider just greying it out instead of removing it.

**Comment by tom-englert** [comment]
> Might consider just greying it out instead of removing it.

Then you would complain that the entry is disabled 😏

**Comment by Hefaistos68** [comment]
Hahaha, well, at least I would know there IS a way to do it, I just did not find it yet.
