### ISSUE TITLE
Option Request: translator order preferences

### ISSUE THREAD

**Issue by Hefaistos68** [tom-englert/ResXResourceManager#272]
When using multiple translators it would be very helpful to set a preference order. Like, after translation one can chose from the dropdown of every translated item which translation to use. Currently the order in this dropdown seems to be the order of the translators on top of the screen. So if I prefer mostly "MS Terminology", still "Azure" will come up always first because its the first one on the screen.

**Comment by tom-englert** [comment]
Actually some translators provide a quality/confidence/rating with their translations, some not. 
Results are sorted by the rating.
For those without (Azure and Google) the rating is hardcoded to 1.0 (s. 61a385a)

If you like this default rating to be configurable, you can submit a PR.
