### ISSUE TITLE
Missing flag in translation when target is Neutral language

### ISSUE THREAD

**Issue by Hefaistos68** [tom-englert/ResXResourceManager#273]
Not sure if thats a bug or intended.

![resx flag](https://user-images.githubusercontent.com/8855055/70540641-84137e80-1b5d-11ea-8694-b3150b7c542b.jpg)

in this case Neutral is Portuguese (first flag in the Target)

**Comment by tom-englert** [comment]
The flag is there, I don't see any missing

**Comment by Hefaistos68** [comment]
In the result rows, usually the language is indicated with the flag, as you can see in this screenshot there is no flag in any row of the results (the small column before the translated text).
