### ISSUE TITLE
Option Request: Show Container

### ISSUE THREAD

**Issue by Hefaistos68** [tom-englert/ResXResourceManager#275]
When you have dozens or even hundreds of forms, you always end up having duplicate keys, like 20 times btnOk.Text with no way to know to which form each one belongs. Going hunting for the form it belongs too is quite tedious.
A simple tooltip would suffice. Or, if you wanna take it over the edge, make a context menu entry "show only keys from this container" or something like that.

**Comment by tom-englert** [comment]
Isn't this exactly what the grouped view does?

**Comment by Hefaistos68** [comment]
Yes, but it doesnt allow you to sort.

**Comment by tom-englert** [comment]
I'm not sure what exactly you are missing, maybe you can just provide a PR?

**Comment by Hefaistos68** [comment]
![resx sort](https://user-images.githubusercontent.com/8855055/70786131-d504bc00-1d83-11ea-9221-46be09203921.jpg)
For example as in this screen shot, make sure all controls with the same name have the same text and if not, check the respective form why its different, or as I 've had the other time, a few of the controls didnt have a resource in some languages at all, again, if so, I wanna know why by checking out the form.
For that I have to know in which form its located.

**Comment by tom-englert** [comment]
just filter by the key of interest and then group...

**Comment by Hefaistos68** [comment]
You are right, this works just fine. (although a tooltip wouldnt hurt :-) )

**Comment by tom-englert** [comment]
Feel free to provide a PR... 😏

**Comment by Hefaistos68** [comment]
Let me get rid of my current workload, then I might get into VS extensions and contribute a bit.

**Comment by tom-englert** [comment]
Or just read the status bar:

![image](https://user-images.githubusercontent.com/10229954/70791860-40f11f80-1d98-11ea-988f-d987b9967183.png)

**Comment by Hefaistos68** [comment]
Reads "Multiple selection" (when "Cell Selection" is on, thats why I didnt see it)

**Comment by tom-englert** [comment]
"Cell Selection" is very limited, you should never turn that on if you don't really need it.

**Comment by Hefaistos68** [comment]
When not using the "Translation" tab, one has to use cell selection and copy/paste from translators. The Translation tab is good but has some limitations.

**Comment by tom-englert** [comment]
Exactly, that is the sole purpose of the cell selection. So when done, turn it off.
