### ISSUE TITLE
Anoyance: ESC doesnt cancel editing in cell, rather closes ResX View

### ISSUE THREAD

**Issue by Hefaistos68** [tom-englert/ResXResourceManager#276]
As said, when editing the contents of a cell, pressing ESC doesnt only cancel the editing but also closes (switches away) ResX. Not expected behavior.

**Comment by tom-englert** [comment]
Can't reproduce

**Comment by Hefaistos68** [comment]
Click on any cell, edit the cell and press ESC. Works with and without cell selection enabled. Also works when editing in the top line edit control.
