### ISSUE TITLE
By default, vb razor views are not used for reference detection.

### ISSUE THREAD

**Issue by IamCloud** [tom-englert/ResXResourceManager#279]
I downloaded this tool to find orphan resource string but it ended up giving me half of my string being orphan. After looking around, I found out my .vbhtml files were not being checked. 

All I had to do was change the Detect Code Reference configuration by adding the .vbhtml file extension to a check:
![image](https://user-images.githubusercontent.com/8987506/70929041-320ca600-2000-11ea-980a-db4b332881c5.png)

It now works fine but I think it would be safe and better to have that by default. There are already rules for vb files. Why not add .vbhtml files.

**Comment by tom-englert** [comment]
@IamCloud Looks you're the first one using this. Isn't ` .vbhtml` case insensitive?

**Comment by IamCloud** [comment]
> 
> 
> @IamCloud Looks you're the first one using this. Isn't ` .vbhtml` case insensitive?

Yes, I believe you are right. Maybe add another record with the same regex but Case Sens. unchecked.
