### ISSUE TITLE
Feature Request: Log Warnings to the Error List window and/or Output window of VisualStudio

### ISSUE THREAD

**Issue by joeyphant** [tom-englert/ResXResourceManager#28]
Would be great if warnings and errors (missing translations, string format mismatches, etc.) could be logged to the VisualStudio ErrorList Window and/or the Output Window.

I'm aware of the "show only lines with warnings and changes" feature but I would really like to see these warnings in the log.

ErrorListProvider might be the way to go: [https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.errorlistprovider(v=vs.140).aspx](url)

**Comment by tom-englert** [comment]
Sounds like a cool feature.

When should it log the errors? Always if the window is open (like e.g. XAML designers), or only during build?

Can you provide a PR for this?

**Comment by joeyphant** [comment]
I would log the errors when opening the solution (if this is possible), when saving the file(s) and during build.

I cannot provide a PR at the moment.

**Comment by tom-englert** [comment]
@yinyue200 some more new strings to translate...
