### ISSUE TITLE
Error Adding new Resource file!

### ISSUE THREAD

**Issue by metheofanis** [tom-englert/ResXResourceManager#281]
Hello, 
I get an error while trying to create a new .resx file for Greek. What do i miss?
Thanks.
Here is the pictures:
![ResXManager](https://user-images.githubusercontent.com/20851608/71477001-65b1b200-27f0-11ea-8d20-587d6dde3075.gif)

![ResXManager](https://user-images.githubusercontent.com/20851608/71477008-69ddcf80-27f0-11ea-8dc9-a2373f8f9f64.jpg)

**Comment by tom-englert** [comment]
I can't reproduce this. Looking at the stack trace this seems to be a VisualStudio problem. 
Did you try to restart VS? 
Did you try to add the file manually?

**Comment by metheofanis** [comment]
Yes, I've restarted VS many times. 
emptied the \AppData\Local\Microsoft\VisualStudio\16.0_e343fe43\Designer\ShadowCache
Installed/Uninstalled ResXManager many times.
Adding the file manually, works as expected.
I've also tried with German. Same errors. 
I looks like it doesn't like me :)
Anyway, thanks.
