### ISSUE TITLE
Improvement: Enable copy/paste to duplicate keys in a file

### ISSUE THREAD

**Issue by pietchaki** [tom-englert/ResXResourceManager#284]
When I Try to copy/paste some resources and the same key already exists in the destination, it does nothing.
I suggest that you allow paste, and mark the new entry as an error or append something to the end of the pasted key. Or maybe open the "New resource key" dialog and paste the values under the new key.

Sometimes I need to include new resources that are similar to ones that we already use, with minor changes to the new ones, and this option would be easier than pasting the row to a spreadsheet document, fixing the values there and then copy and pasting back to the manager.

**Comment by tom-englert** [comment]
If the key already exists, the content will be replaced - so your request would conflict with an already existing feature.

**Comment by pietchaki** [comment]
Ok, it does makes sense why I got nothing when copy/pasting in same files now...
Thanks anyway!
