### ISSUE TITLE
Key: Name charset

### ISSUE THREAD

**Issue by semirci** [tom-englert/ResXResourceManager#287]
You need to use "üÜşşğıiÇçÖö" and similar characters as key.

For Example :  Bugün Benim Neşeli Bir Günüm
@Resources.BugünBenimNeşeliBirGünüm -> @Resources.Bugun_Benim_Neseli_Bir_Gunum

**Comment by tom-englert** [comment]
Code behind is generated by VisualStudio. 
You can switch to [CustomCodeGenerator](../wiki/Custom-Code-Generator) to create your own.
