### ISSUE TITLE
No language showing in column chooser

### ISSUE THREAD

**Issue by fgasnier71** [tom-englert/ResXResourceManager#288]
Exact same problem as described in issue #169.
* I uninstalled and reinstalled the extension but it did not work for me,
* I suspect the languages are not displayed because the drop-down window seems to be reduced to a 1x1 pixel size under the tool button when it is clicked.
![image](https://user-images.githubusercontent.com/1512039/72522709-9e2c3500-385e-11ea-8415-cb2f7fded54f.png)

**Comment by tom-englert** [comment]
So that was the solution to #169:
> Yeah, I don't know how but it worked somehow the next day.

Do you have the same problem in the standalone version?

**Comment by tom-englert** [comment]
Also can you share a bigger screenshot that shows the available languages?

**Comment by tom-englert** [comment]
No response
