### ISSUE TITLE
.Net Core Project Regex Help for Detect Code References

### ISSUE THREAD

**Issue by afatih** [tom-englert/ResXResourceManager#292]
I'm working on ASP .Net Core MVC project. I want to use Detect Code References but i didn't find true regex pattern. Can anyone help me?
![regex1](https://user-images.githubusercontent.com/51159689/73260746-9748df00-41db-11ea-93d2-2d8bc5a78a37.jpg)

**Comment by tom-englert** [comment]
What does the code look like that you are trying to match?

**Comment by afatih** [comment]
![ss4](https://user-images.githubusercontent.com/51159689/73269617-35de3b80-41ee-11ea-9bdb-a554f68ea0a8.jpg)
I used that keys in my Controllers or Views. But there are more den 700 keys all my resources files and most of them unused.

**Comment by tom-englert** [comment]
So write a Regex that finds SharedLocalizer["$Key"], what's the problem with this?

**Comment by afatih** [comment]
![ss7](https://user-images.githubusercontent.com/51159689/73271922-86579800-41f2-11ea-8c22-9519f89edb84.jpg)

I used that but still there is no match. Also there are 2 different usage of SharedLocalizer. One of them is _sharedLocalizer["key"] and other one is SharedLocalizer["key"]. Can you help me to write true Regex expression please .

**Comment by tom-englert** [comment]
RTFM - you must escape the square brackets

**Comment by afatih** [comment]
This is my first time to use Regex. Before wrote you i read some documents but actually i don't understand very well. I know you are a professional and its not a big deal for you but still i am trying to dosomething. Anyway you help me a lot. Thank you so much ^^.

**Comment by tom-englert** [comment]
that should work: _?[Ss]haredLocalizer\["($Key)"\]

**Comment by afatih** [comment]
It's absolutely work. Thank you so much sir ^^
