### ISSUE TITLE
Feature Request - Export to Workbook with one language per Sheet

### ISSUE THREAD

**Issue by riverar** [tom-englert/ResXResourceManager#294]
Would love to share an exported workbook for community-driven localization of our open source project. To make it easier for users to drill down into the languages they wish to contribute to, it'd be nice if ResXResourceManager exported each language to its own sheet.

I'm open to any alternatives.

**Comment by tom-englert** [comment]
Maybe use the scripting engine and write a simple script for this, instead of bloating the UI?

**Comment by riverar** [comment]
@tom-englert oh, I had no clue there was a scripting engine! My mistake. Will definitely check this out tomorrow, thank you!

**Comment by tom-englert** [comment]
@riverar any feedback? Can this be closed?

**Comment by riverar** [comment]
@tom-englert Closing. Scripting engine is more than adequate.
