### ISSUE TITLE
UI Improvements - do not display certain strings in "Only warnings" mode

### ISSUE THREAD

**Issue by ekuchynski** [tom-englert/ResXResourceManager#295]
If a source string contains just a space and is marked as Invariant, it is still displayed in the "Show only lines with warnings or changes" mode. See screenshot:
![Screenshot](https://i.ibb.co/60vSRhZ/ex.png)

**Comment by tom-englert** [comment]
This isintended to identify stale resources with no content.
This would need a new flag like e.g. "Intentionally Empty".
