### ISSUE TITLE
How to switch to english interface

### ISSUE THREAD

**Issue by Sonic3R** [tom-englert/ResXResourceManager#297]
Hi,

I don't understand german and I want to switch to English to understand the meaning of buttons from toolbar.

How to change language ?

**Comment by tom-englert** [comment]
It's using the Visual Studios / Operating Systems UI language. There is actually no way to show English ResXManager on a German system.

**Comment by adv12** [comment]
@Sonic3R may be referring to the standalone app.  It comes up in German for me, too, and my OS is set to English.

**Comment by tom-englert** [comment]
@adv12, @Sonic3R  are you using the standalone version from the click-once deployment?

**Comment by Sonic3R** [comment]
I used a compiled app from Visual Studio 2019

**Comment by tom-englert** [comment]
https://github.com/tom-englert/ResXResourceManager/blob/6ba9506c95e45c05e2e95a8c141d2d8ccf6f21d4/ResXManager/App.xaml.cs#L28-L32

**Comment by Sonic3R** [comment]
It happens in Release (when publish app as installer) too. I will change in code to use always EN

**Comment by tom-englert** [comment]
When I use the official click once, it shows English on non-German systems
