### ISSUE TITLE
Feature Request - "Intellisense" for indexing resx keys

### ISSUE THREAD

**Issue by BrayanKhosravian** [tom-englert/ResXResourceManager#298]
What about using some sort of intellisense for indexing resx keys.

A possible way to do that:

Provide an additional nuget which has a static class and 1 method, looking something like this:
(It is just an example)

```cs
public static class ResXManager
{
     public static string GetString(string key, string language)
    {
          // code to get the value by indexing the row with the key and the column with the language
    }
}

```

So when the user calls the method like this: 
`myButton.Text = ResXManager.GetString("xxxx", "de")`
The user could get some visual feedback looking like intellisense.

Example:
user calls `ResXManager.GetString("Err", )`
And intellisense shows all keys which begin with "Err" and the output is sorted alphabetically.
(Probably only loading 10 keys and use some sort of caching or lazy evaluation when displaying the content to the user)

And have some bool option in the resx manager interface to enable/disable this feature.
So when the nuget is not in the soltuion this feature should not be activateable.

I tought about implementing that for myself as an external extension, but it might fit here better.

A few questions:
1.) is this even possible to implement?
2.) If yes, do you want to merge such a feature into your solution?

Thanks in advance.

Sincerely
Brayan

**Comment by tom-englert** [comment]
This is exactly what you already have in the `<resource-name>.designer.cs`. 
What are you missing?

**Comment by BrayanKhosravian** [comment]
Oh yes i just noticed that its possible to generate a code behind of a resx file using the resx manager.

Using this simple file:
![image](https://user-images.githubusercontent.com/35541212/75645024-bad0d080-5c44-11ea-84c5-94b2abc67dae.png)

Whit the generated code behind file its possible to get the value of the cells like this:
![image](https://user-images.githubusercontent.com/35541212/75645148-1733f000-5c45-11ea-8e00-5ff99fb5d2c4.png)

Where `GetString` gets the string by passing the key and culture.
And all the keys are accessible with read-only properties.
Its interesting that the code behind gets re-generated when saving the resx file.

I still got a few questions:
- What if we use multiple resx files and we want to index a value on both files?
Is there a way to achieve that?

**Comment by tom-englert** [comment]
How would you "index a value on both files"? I don't get what you want to accieve.
