### ISSUE TITLE
String format and trailing punctation result in many false positives

### ISSUE THREAD

**Issue by nk111** [tom-englert/ResXResourceManager#299]
I've three languages in my project. When i enable "Show only lines with warnings or changes" i see a lot of lines without any visible error. There is nothing marked red but the lines show up. 

I can only manage to hide these lines by disabling these two consistency checks:

1. Matching string format parameters
2. Trailing punctation
3. Trailing whitespace

For me the rules seem to be ok for the three columns. There is no red mark on each of the 3 cells.

Actually i see lots of rows that actually have a trailing punctation or trailing whitespace but it's consistent in all three languages. So the row should not be displayed at all?!

Could this somehow be because i've disabled the comment and neutral columns? I don't have a neutral language and no comments.

**Comment by tom-englert** [comment]
A neutral language is mandatory
