### ISSUE TITLE
ResX Resource Manager  can't show "Main "! 

### ISSUE THREAD

**Issue by maikebing** [tom-englert/ResXResourceManager#3]
![image](https://cloud.githubusercontent.com/assets/3445167/23226828/ff7422d4-f971-11e6-9ef9-f14577a14b96.png)

ResX Resource Manager loaded.
Home: http://resxresourcemanager.codeplex.com/
Report issues: http://resxresourcemanager.codeplex.com/workitem/list/basic
Support the project by adding a short review: http://visualstudiogallery.msdn.microsoft.com/3b64e04c-e8de-4b97-8358-06c73a97cc68/view/Reviews
Error: System.Windows.Markup.XamlParseException: 设置属性“System.Windows.ResourceDictionary.DeferrableContent”时引发了异常。 ---> System.Xaml.XamlObjectWriterException: 设置属性“System.Windows.ResourceDictionary.DeferrableContent”时引发了异常。 ---> System.Xaml.XamlObjectWriterException: 在“MS.Internal.Markup.StaticExtension”上提供值时引发了异常。 ---> System.ArgumentException: 无法将“TomsToolbox.Wpf.ResourceKeys.AutoToolTipTextBoxStyleKeyName”StaticExtension 值解析为枚举、静态字段或静态属性。
   在 System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   在 MS.Internal.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- 内部异常堆栈跟踪的结尾 ---
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   在 System.Xaml.XamlObjectWriter.Logic_ProvideValue(ObjectWriterContext ctx)
   在 System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(ObjectWriterContext ctx)
   在 System.Xaml.XamlObjectWriter.WriteEndObject()
   在 System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   在 System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   在 System.Windows.ResourceDictionary.EvaluateMarkupExtensionNodeList(XamlReader reader, IServiceProvider serviceProvider)
   在 System.Windows.ResourceDictionary.GetKeyValue(KeyRecord key, IServiceProvider serviceProvider)
   在 System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   在 System.Windows.ResourceDictionary.SetDeferrableContent(DeferrableContent deferrableContent)
   在 System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__297_0(Object target, Object value)
   在 System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- 内部异常堆栈跟踪的结尾 ---
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   在 MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.SetValue(Object obj, XamlMember property, Object value)
   在 System.Xaml.XamlObjectWriter.Logic_ApplyPropertyValue(ObjectWriterContext ctx, XamlMember prop, Object value, Boolean onParent)
   在 System.Xaml.XamlObjectWriter.Logic_DoAssignmentToParentProperty(ObjectWriterContext ctx)
   在 System.Xaml.XamlObjectWriter.WriteEndMember()
   在 System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   在 System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   在 System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter)
   在 System.Windows.SystemResources.ResourceDictionaries.LoadDictionary(Assembly assembly, String assemblyName, String resourceName, Boolean isTraceEnabled, Uri& dictionarySourceUri)
   在 System.Windows.SystemResources.ResourceDictionaries.LoadGenericDictionary(Boolean isTraceEnabled)
   在 System.Windows.SystemResources.FindDictionaryResource(Object key, Type typeKey, ResourceKey resourceKey, Boolean isTraceEnabled, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean& canCache)
   在 System.Windows.SystemResources.FindResourceInternal(Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference)
   在 System.Windows.FrameworkElement.FindResourceInternal(FrameworkElement fe, FrameworkContentElement fce, DependencyProperty dp, Object resourceKey, Object unlinkedParent, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, DependencyObject boundaryElement, Boolean isImplicitStyleLookup, Object& source)
   在 System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   在 System.Windows.StaticResourceExtension.FindResourceInEnviroment(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   在 System.Windows.StaticResourceExtension.TryProvideValueInternal(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   在 System.Windows.ResourceDictionary.SetOptimizedStaticResources(IList`1 staticResources, IServiceProvider serviceProvider, StaticResourceExtension staticResourceWorker)
   在 System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   在 System.Windows.ResourceDictionary.SetDeferrableContent(DeferrableContent deferrableContent)
   在 System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__297_0(Object target, Object value)
   在 System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   在 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   在 System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   在 tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() 位置 C:\Agent\_work\3\s\Main\ResXManager.View\Visuals\ResourceView.xaml:行号 1
   在 tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ExportProvider exportProvider) 位置 C:\Agent\_work\3\s\Main\ResXManager.View\Visuals\ResourceView.xaml.cs:行号 52
Error: System.Windows.Markup.XamlParseException: 在“System.Windows.StaticResourceExtension”上提供值时引发了异常。 ---> System.Xaml.XamlObjectWriterException: 设置属性“System.Windows.ResourceDictionary.DeferrableContent”时引发了异常。 ---> System.Xaml.XamlObjectWriterException: 在“MS.Internal.Markup.StaticExtension”上提供值时引发了异常。 ---> System.ArgumentException: 无法将“TomsToolbox.Wpf.ResourceKeys.AutoToolTipTextBoxStyleKeyName”StaticExtension 值解析为枚举、静态字段或静态属性。
   在 System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   在 MS.Internal.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- 内部异常堆栈跟踪的结尾 ---
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   在 System.Xaml.XamlObjectWriter.Logic_ProvideValue(ObjectWriterContext ctx)
   在 System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(ObjectWriterContext ctx)
   在 System.Xaml.XamlObjectWriter.WriteEndObject()
   在 System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   在 System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   在 System.Windows.ResourceDictionary.EvaluateMarkupExtensionNodeList(XamlReader reader, IServiceProvider serviceProvider)
   在 System.Windows.ResourceDictionary.GetKeyValue(KeyRecord key, IServiceProvider serviceProvider)
   在 System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   在 System.Windows.ResourceDictionary.SetDeferrableContent(DeferrableContent deferrableContent)
   在 System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__297_0(Object target, Object value)
   在 System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- 内部异常堆栈跟踪的结尾 ---
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   在 MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.SetValue(Object obj, XamlMember property, Object value)
   在 System.Xaml.XamlObjectWriter.Logic_ApplyPropertyValue(ObjectWriterContext ctx, XamlMember prop, Object value, Boolean onParent)
   在 System.Xaml.XamlObjectWriter.Logic_DoAssignmentToParentProperty(ObjectWriterContext ctx)
   在 System.Xaml.XamlObjectWriter.WriteEndMember()
   在 System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   在 System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   在 System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter)
   在 System.Windows.SystemResources.ResourceDictionaries.LoadDictionary(Assembly assembly, String assemblyName, String resourceName, Boolean isTraceEnabled, Uri& dictionarySourceUri)
   在 System.Windows.SystemResources.ResourceDictionaries.LoadGenericDictionary(Boolean isTraceEnabled)
   在 System.Windows.SystemResources.FindDictionaryResource(Object key, Type typeKey, ResourceKey resourceKey, Boolean isTraceEnabled, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean& canCache)
   在 System.Windows.SystemResources.FindResourceInternal(Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference)
   在 System.Windows.FrameworkElement.FindResourceInternal(FrameworkElement fe, FrameworkContentElement fce, DependencyProperty dp, Object resourceKey, Object unlinkedParent, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, DependencyObject boundaryElement, Boolean isImplicitStyleLookup, Object& source)
   在 System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   在 System.Windows.StaticResourceExtension.FindResourceInEnviroment(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   在 System.Windows.StaticResourceExtension.TryProvideValueInternal(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   在 System.Windows.StaticResourceExtension.ProvideValueInternal(IServiceProvider serviceProvider, Boolean allowDeferredReference)
   在 System.Windows.StaticResourceExtension.ProvideValue(IServiceProvider serviceProvider)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   在 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   在 System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   在 tomenglertde.ResXManager.View.Visuals.TranslationsView.InitializeComponent() 位置 C:\Agent\_work\3\s\Main\ResXManager.View\Visuals\TranslationsView.xaml:行号 1
   在 tomenglertde.ResXManager.View.Visuals.TranslationsView..ctor(ExportProvider exportProvider) 位置 C:\Agent\_work\3\s\Main\ResXManager.View\Visuals\TranslationsView.xaml.cs:行号 33
Assembly location: C:\Users\Silas\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\jqe51gya.co4
Version: 1.0.0.93
DTE event: Document saved
DTE event: Document saved
DTE event: Document saved
DTE event: Document saved
DTE event: Document opened

**Comment by tom-englert** [comment]
I think you have another of my extensions installed (e.g. Wax), and this bug appears depending on in which order the windows of both are loaded. After restarting VS it should be fine again.

This is due to https://connect.microsoft.com/VisualStudio/feedback/details/2993889/wpf-fails-to-load-resources-if-two-versions-of-the-same-assembly-are-loded

Microsoft has confirmed this to be a bug, but it's not decided whether they are going to fix it. Maybe you can vote for it and click the link on "repros" to give it some more importance.

**Comment by maikebing** [comment]
V 1.0.0.92   is well!
only V 1.0.0.93  found this   error!

So what is the change between version 1.0.0.93 and version V 1.0.0.92 ?

**Comment by tom-englert** [comment]
Yes, both are using https://github.com/tom-englert/TomsToolbox.
I'll have to update wax to use the same version as ResXManager.

**Comment by maikebing** [comment]
try this ?
```
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Net.FtpClient" publicKeyToken="fa4be07daa57c2b7" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.0.5824.34026" newVersion="1.0.5824.34026" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.6.10.0" newVersion="2.6.10.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.6.10.0" newVersion="2.6.10.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.29.0" newVersion="2.2.29.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

**Comment by tom-englert** [comment]
Patch the app.config of Visual Studio?

**Comment by maikebing** [comment]
http://stackoverflow.com/questions/25792540/sidebyside-error-with-binding-redirect-in-net-windows-service
```
 public static class BindingRedirects
{
    static readonly Dictionary<string, string> Redirects = new Dictionary<string, string>
    {
        { "AutoMapper, Version=3.2.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005", @"AutoMapper.3.2.1\AutoMapper.dll"}    
    }; 

    public static void Register()
    {
        AppDomain.CurrentDomain.AssemblyResolve += (o, args) =>
        {
            if (Redirects.ContainsKey(args.Name))
            {
                var path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, Redirects[args.Name]);
                return Assembly.LoadFrom(path);
            }

            return null;
        }; 
    }
}
```

**Comment by tom-englert** [comment]
But this is not a side-by-side error. Side-by-side works great in this scenario- except for the resource bug in WPF - because every extension exists in a separate folder.

To solve this problem with the above sample, any VS extension would need to scan all other extensions when loaded, check their dependencies, load the dependent assemblies of another extensions if it provides a newer version and create a dynamic binding redirect for the other version.

However a VS extension won't even know what other extensions are installed, only VS knows this and it does not expose it.

**Comment by maikebing** [comment]
It is trouble.

**Comment by tom-englert** [comment]
If you have the latest versions of all extensions, this should be no problem any more. 
Can you confirm this?

**Comment by maikebing** [comment]
It's OK!
