### ISSUE TITLE
@invariant in Excel 

### ISSUE THREAD

**Issue by sarchese** [tom-englert/ResXResourceManager#302]
Can I prevent resources marked as @invariant from appearing in the Excel file when exporting?
I tried this but don't work:
$noInvariants = $allEntries | 
	Where-Object { $_.Comment -ne '@Invariant'  }
    
# Write-Host ($changes | Format-Table | Out-String)
    
    
foreach ($culture in $myhost.ResourceManager.Cultures) {
    if ($culture -ne '') {
        $excelFilename = Join-Path $outFolder "XXXX.$ccnetVersion$culture.xlsx"
        $excelFilename
        $myhost.ExportExcel($excelFilename, $noInvariants, @("", $culture))
    }
}

thx :)

**Comment by tom-englert** [comment]
should be `@Invariant`, and condition should be "contains", not "equals"

**Comment by sarchese** [comment]
Hi, thank for your help!!
I tried this but it doesn't work either:
$noInvariants = $allEntries | 
	Where-Object { $_.Comment -contains '@Invariant'  }
I guess there is a problem elsewhere.

**Comment by tom-englert** [comment]
Yes, you did not fix the typo in Invariant - it's camel case!
