### ISSUE TITLE
Horizontal scroll not working

### ISSUE THREAD

**Issue by oestrogen** [tom-englert/ResXResourceManager#305]
Horizontal scrolling is not working. We translate into ~30 languages, so there's a lot of horizontal scrolling needed.

Tested on a ThinkPad T460 running Windows 10 with:
- built-in trackpad
- built-in TrackPoint
- Apple Magic Mouse
- generic Lenova mouse (vertical scroll-wheel with shift key pressed)

**Comment by tom-englert** [comment]
Just show only the columns you're currently working on, and hide the others.

**Comment by oestrogen** [comment]
Thanks for the suggestion, @tom-englert, but...

First of all, when working with a single string I am working with _all_ the columns.

Secondly, it is very tedious to turn on and off what columns to show. Since there is no "show/hide all columns" I have to manually go through the drop down list of 60 elements (Two for each language, value and comment) and be careful to only click every other checkbox (the non-comment ones).

![image](https://user-images.githubusercontent.com/351057/76404535-ec554480-6386-11ea-90bd-477193d74f50.png)

**Comment by tom-englert** [comment]
If you need all columns, then try to limit the number of rows by selecting only one project or by filtering.

For the column-selector: happy to accept your PR to make the user experience better for this.

**Comment by tom-englert** [comment]
BTW you could also share the link to this project, so I can do some performance testing.
