### ISSUE TITLE
Reference count

### ISSUE THREAD

**Issue by devsamt** [tom-englert/ResXResourceManager#313]
Please, can you increment reference count when:
`using R = Product.Properties.Resources;`
`MessageBox.Show(R.HelloWorld);`
Actually, `HelloWorld` reference count is 0.

**Comment by tom-englert** [comment]
Just add your individual pattern in the configuration tab

**Comment by devsamt** [comment]
I can write an approximate pattern but not a valid pattern...
What would be the correct pattern according to you ?

**Comment by devsamt** [comment]
That will be enough, thank you for your help !
