### ISSUE TITLE
Don't change solution file every time

### ISSUE THREAD

**Issue by digocesar** [tom-englert/ResXResourceManager#32]
I had change my default language to portuguese and this information is saved into solution file, link this:
```
GlobalSection(ExtensibilityGlobals) = postSolution
	RESX_NeutralResourcesLanguage = pt-BR
	RESX_PrefixTranslations = False
EndGlobalSection
```
But every time I change a resource with resxmanager the VisualStudio changes the configuration position in solution file, like this:
```
GlobalSection(ExtensibilityGlobals) = postSolution
	RESX_PrefixTranslations = False
	RESX_NeutralResourcesLanguage = pt-BR
EndGlobalSection
```
It's possible to save this preference only when I was changed and avoid Visual Studio changes the solution file every time?

**Comment by tom-englert** [comment]
@digocesar are you sure this changes every time you change a resource? 
Actually it changes every time you change the configuration, ore something else in the solution. 
However I have no control about the order of the entries, this is handled by VisualStudio.
To avoid this you may change the global defaults, so it does not need to write the configuration into the solution.

**Comment by digocesar** [comment]
I'm using Visual Studio 2013 Professional. It's just me that have this situation!?
If I open the project, open ResxManager, and change some resource, the solution file is changed.

**Comment by tom-englert** [comment]
I never experienced this, and the feature is in since VS2010. 
As long as you don't change any configuration value, ResXManager does not actively touch the solution. 
Maybe there is some other plugin causing the solution to change?
