### ISSUE TITLE
Feature:  Optional TextWrapping

### ISSUE THREAD

**Issue by JD-Robbs** [tom-englert/ResXResourceManager#33]
A checkbox/toggleButton to optionally activate text wrapping for long one-liners would be a nice UX improvement.  Currently, while translating, I keep giving focus back to the neutral string to view it in the resizable preview panel at the top.

Amazing tool, keep up the great work!

**Comment by tom-englert** [comment]
@yinyue200 can you please add the Chinese translation for the new tool tip?

**Comment by yinyue200** [comment]
@tom-englert ok
