### ISSUE TITLE
Blank cell in excel is not imported

### ISSUE THREAD

**Issue by Sokti** [tom-englert/ResXResourceManager#35]
Blank cell in excel-sheet is ignored while importing. So it is not possible to remove translated text in resources by excel import.

**Comment by tom-englert** [comment]
Yes, that's intended, it merges the existing with the excel - otherwise you would erase everything that's not in the excel sheet, if it is not a full export.

**Comment by Sokti** [comment]
I'm using an excel-sheet as leading source for the project translations. It would be nice to have a setting to change this behaviour. But if it's intendet to not override.. this issue can be closed.

Thanks for your reply and keep it up!
