### ISSUE TITLE
Really slow on save

### ISSUE THREAD

**Issue by MauroMon** [tom-englert/ResXResourceManager#36]
Hi all.
After last update my visual studio 2015 became really slow on save, even if no change to file is made.
If i disable resx manager vs works fine.
Is there any way i can help?

Thank you

**Comment by tom-englert** [comment]
What exactly is "on save" - saving any file? 
And how do you save files without changes?

**Comment by MauroMon** [comment]
every time i hit control + shift +s in visual studio

**Comment by tom-englert** [comment]
I can't reproduce this, do you have any other hints?

**Comment by Macy-Soft** [comment]
I work with VS2017. Since the last update, I also have such a problem. I'm adding a new key. The I click in a field to change, VS2017 hangs up. It seems to go into an endless loop. The memory consumption increases to infinity.

**Comment by TeaDrivenDev** [comment]
We're seeing this too on all machines with 2017, both with 1.5.66 and 1.5.679. I went back to 1.4 for the time being.

**Comment by tom-englert** [comment]
Can someone try to debug this, to see where it is hanging?

**Comment by tom-englert** [comment]
Please try the latest build from http://vsixgallery.com/

**Comment by TeaDrivenDev** [comment]
Works for me. Thanks!

**Comment by MauroMon** [comment]
For me don't work.
Here is the output on ctrl, shift, s hit:

DTE event: Document saved
>>> 12: ResourceManager.Load @08:33:05.8
>>> 13: Enumerate source files @08:33:05.8
<<< 13: Enumerate source files 00:00:00.3929649
<<< 12: ResourceManager.Load 00:00:02.1900611
DTE event: Document saved
>>> 14: ResourceManager.Load @08:33:08.1
>>> 15: Enumerate source files @08:33:08.1
<<< 15: Enumerate source files 00:00:00.3843774
<<< 14: ResourceManager.Load 00:00:02.4149141
DTE event: Document saved
>>> 16: ResourceManager.Load @08:33:10.7
>>> 17: Enumerate source files @08:33:10.7
<<< 17: Enumerate source files 00:00:00.4210786
<<< 16: ResourceManager.Load 00:00:02.4470392
DTE event: Document saved
>>> 18: ResourceManager.Load @08:33:13.3
>>> 19: Enumerate source files @08:33:13.3
<<< 19: Enumerate source files 00:00:00.3920325
<<< 18: ResourceManager.Load 00:00:02.6600234
DTE event: Document saved
>>> 20: ResourceManager.Load @08:33:16.0
>>> 21: Enumerate source files @08:33:16.0
<<< 21: Enumerate source files 00:00:00.3879737
<<< 20: ResourceManager.Load 00:00:02.5692937
DTE event: Document saved
>>> 22: ResourceManager.Load @08:33:18.7
>>> 23: Enumerate source files @08:33:18.7
<<< 23: Enumerate source files 00:00:00.4095491
<<< 22: ResourceManager.Load 00:00:02.5848014
DTE event: Document saved
>>> 24: ResourceManager.Load @08:33:21.4
>>> 25: Enumerate source files @08:33:21.4
<<< 25: Enumerate source files 00:00:00.4269512
<<< 24: ResourceManager.Load 00:00:02.5393931
DTE event: Document saved
>>> 26: ResourceManager.Load @08:33:24.0
>>> 27: Enumerate source files @08:33:24.0
<<< 27: Enumerate source files 00:00:00.4165160
<<< 26: ResourceManager.Load 00:00:03.1074499
>>> 28: Enumerate source files @08:33:27.2
<<< 28: Enumerate source files 00:00:00.4078452

Hope can help
