### ISSUE TITLE
Error in installing ResXResourceManager

### ISSUE THREAD

**Issue by irenechan0208** [tom-englert/ResXResourceManager#37]
Hello HelpDesk, 

I have encountered the below error when installing the ResX Resource Manager

https://github.com/tom-englert/ResXResourceManager

![error_resx](https://user-images.githubusercontent.com/31917437/30365994-30f99586-989c-11e7-8191-dfeb15e97590.PNG)

May i know how to solve it?

Thanks, 
Irene

**Comment by Yeah69** [comment]
I get this error as well.

**Comment by tom-englert** [comment]
Which version do you install? Standalone, Visual Studio Extension or Scripting?

**Comment by Yeah69** [comment]
Standalone/Click-Once

**Comment by tom-englert** [comment]
OK, found it. Binaries are updated.

**Comment by Yeah69** [comment]
Works again. Thank you a lot for the fast support.
