### ISSUE TITLE
The resource isn't recognized

### ISSUE THREAD

**Issue by samuelmelo** [tom-englert/ResXResourceManager#40]
I cannot open a resource, using Visual Studio. When I click to view a .resx on ResX Resource Manager it just simply don't open and I can't figure out what's going on.

**Comment by tom-englert** [comment]
I there any information in the output window?

**Comment by samuelmelo** [comment]
Hey, thank you Tom. I just relized that were 3 or 4 duplicate keys.

**Comment by tom-englert** [comment]
😄
