### ISSUE TITLE
Unresponsiveness on large resources

### ISSUE THREAD

**Issue by FreHu** [tom-englert/ResXResourceManager#42]
I have some large individual resources (e-mail templates, cca. 11k characters). ResX manager hangs completely when trying to open them and the only solution is killing visual studio. The same happens with the standalone version. 

I can get it to at least export the resource (by never double clicking so I don't go into edit mode) so I can edit it in excel and import it back, but even this can take a long time.

While not the best use case for resx files, the default VS resource editor can handle them. Is there any chance some optimizations could be made?

**Comment by tom-englert** [comment]
I have analyzed it and found the bottle neck, there will be a fix in the next days.

**Comment by FreHu** [comment]
I will get a chance to test it next week, thanks!
