### ISSUE TITLE
System.Runtime.InteropServices.COMException at save

### ISSUE THREAD

**Issue by Solethia** [tom-englert/ResXResourceManager#44]
Ran into this error today, while trying to save changes after adding a single resource key.

![image](https://user-images.githubusercontent.com/5747583/31217658-02452ef8-a9b8-11e7-9993-d7ca281b95e8.png)

Edit: It seems to have saved the changes, despite the error.

**Comment by tom-englert** [comment]
This is not critical, you can ignore this. I will avoid this in the next version.

Is this reproducible, or just happend once?

**Comment by Solethia** [comment]
Happened twice. Stopped after a restart. Was as you said not critical so didn't use too much time testing.
