### ISSUE TITLE
Languages tab - some English variants impossible to see in Win10

### ISSUE THREAD

**Issue by AlanWidmer** [tom-englert/ResXResourceManager#46]
The `Languages` tab doesn't appear to have a way to scroll vertically. So some of the English language variants are not visible as they are off the bottom of the screen. 
On my monitor, even with the app maximized, the last English variant I see is en-LS.
I tried scrolling using down arrow, page down, mouse scroll wheel.
If I reduce the size of the program window other languages with lots of cultures are also truncated.

See this image for an example ![resx languages issue](https://user-images.githubusercontent.com/741628/31589469-d6d38178-b1b6-11e7-9910-54f261ab2e6e.PNG)

**Comment by tom-englert** [comment]
Hi Alan,

No, the languages tab wraps vertically and scrolls horizontally.
And I don’t have en-LS.

What size is your screen? I could only see some clipping if the window is <600px height.

BR
Tom

Von: Alan Widmer [mailto:notifications@github.com]
Gesendet: Sonntag, 15. Oktober 2017 23:43
An: tom-englert/ResXResourceManager <ResXResourceManager@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [tom-englert/ResXResourceManager] Languages tab - some English variants impossible to see (#46)


The Languages tab doesn't appear to have a way to scroll vertically. So some of the English language variants are not visible as they are off the bottom of the screen.
On my monitor, even with the app maximized, the last English variant I see is en-LS.
I tried scrolling using down arrow, page down, mouse scroll wheel.
If I reduce the size of the program window other languages with lots of cultures are also truncated.

See this image for an example [resx languages issue] <https://user-images.githubusercontent.com/741628/31589469-d6d38178-b1b6-11e7-9910-54f261ab2e6e.PNG>

**Comment by AlanWidmer** [comment]
My monitor resolution is 2560 x 1440
I am using Windows10 Build 16299.19 AKA Fall Creators Update 1709. I did not install additional language packs.

**Comment by tom-englert** [comment]
I see, it's Win10 adding so many new languages. 
If someone has an idea how to fix this with reasonable effort, help would be appreciated.
