### ISSUE TITLE
ListViewItem.Text

### ISSUE THREAD

**Issue by Michael-Heimann** [tom-englert/ResXResourceManager#47]
Is it possible to add ListViewItem.Text to the translatable resources? I know it's saved as a binary blob, but it would be really useful to my project.

**Comment by tom-englert** [comment]
I have no clue how this could work...

**Comment by Michael-Heimann** [comment]
Probably with the  ListViewItem.Serialize(...) ListViewItem.Deserialize(...) methods?

**Comment by tom-englert** [comment]
If you find a good solution that does not hinder the other features you could provide a PR.

**Comment by tom-englert** [comment]
I think this request is out of scope, ResXManager can't control how resources are generated from code.
