### ISSUE TITLE
Resource reference not found in MasterPage

### ISSUE THREAD

**Issue by codeweb** [tom-englert/ResXResourceManager#48]
The resource "Atomi" has 0 references but it's presente in master page.

![1](https://user-images.githubusercontent.com/2588370/31811753-01019d40-b581-11e7-8272-5056fd5496a7.png)
![2](https://user-images.githubusercontent.com/2588370/31811754-012073dc-b581-11e7-89c1-5d43efd7f1b3.png)

**Comment by codeweb** [comment]
Solution is adding .Master in Configuration. Together with aspx, ascx. Can you add it by default?
Thanks

**Comment by tom-englert** [comment]
![image](https://user-images.githubusercontent.com/10229954/31825093-5e860e9e-b5b1-11e7-82f2-b33d0c033bfa.png)


like this?

**Comment by codeweb** [comment]
If it's case insensitive, yep!
