### ISSUE TITLE
Resources reference: only selected files

### ISSUE THREAD

**Issue by codeweb** [tom-englert/ResXResourceManager#49]
Resources reference have to work only on selected files, not all files.

**Comment by tom-englert** [comment]
@codeweb can you be more specific, please?

**Comment by codeweb** [comment]
The reference count is referred to all files, not only selected.
(In the image there is only one file; try using two files and select only one: references count won't change)

![2017-10-20_1633](https://user-images.githubusercontent.com/2588370/31826154-9455441a-b5b4-11e7-9a1d-47d30a7337f8.png)

**Comment by tom-englert** [comment]
These are not related: 
- On the left side you are selecting resource files (.resx). 
- References are counted in all files except resource files.
