### ISSUE TITLE
***.Designer.cs for .resx file doesn't update after .resx file modification

### ISSUE THREAD

**Issue by paulem** [tom-englert/ResXResourceManager#51]
I use version 1.8.767.

After adding a new key in .resx file through ResX Manager code-behind file regeneration doesn't occur. It happens only if I open .resx file and change Access Modifier setting.

**Comment by nomba** [comment]
I have the same problem. (_VS 2017 Enterprise 15.4.1_)

**Comment by studiounlimited** [comment]
For what it's worth: I'm also experiencing this (VS 2017 Enterprise 15.4.1)

**Comment by vankhangfet** [comment]
I have the same problem (VS 2015 Professional ver 14.0.24720.00 Update1).

**Comment by rama21385** [comment]
Same problem VS Prof 2017 v15.4.1
or is it a problem with Win10 Creators which I updated last week and since then it doesn't do it?
Current workaround is to create the resource string with VS itself and then do all the translation using your tool.

**Comment by niwred** [comment]
Same Problem here. VS Professional 2017 Professional 15.4.1

**Comment by LiborSo** [comment]
Same problem. VS Community 2017 15.4.0
I need everytime to change modifier of the ResX file to "No code generation" then back to "Public".

**Comment by raztus** [comment]
Having this problem today.

**Comment by ivantrouvetout** [comment]
same problem 
ResXManager v1.32.1682
visual studio 15.9.4

resx file in public acces

**Comment by ivantrouvetout** [comment]
> 
> 
> same problem
> ResXManager v1.32.1682
> visual studio 15.9.4
> 
> resx file in public acces

I uninstal reinstal and it work

**Comment by CedricFluegge** [comment]
same problem
v 1.85.6305.0
