### ISSUE TITLE
'Clean-up'

### ISSUE THREAD

**Issue by McOldSchool** [tom-englert/ResXResourceManager#52]
Working with ResXResourceManager is saving a lot of time. Unfortunately the development progress is fast and once used values are gone in the next version from the main .resx-file leading to not used translation in other language .resx-file remain.

So I'm wondering if it is possible to add some kind of 'clean-up' function to this awesome tool, removing entries from translated resx-files if the corresponding one in the 'main'-resx file is gone.

**Comment by tom-englert** [comment]
Just sort by the neutral language column, then all empty entries will be on top, so you can just mark and delete them.

**Comment by McOldSchool** [comment]
Thanks for the reply, but I was already aware of this possibility. The issue with it is, that VB and the used devex are also creating empty entries. If I'm going to delete those, the program will crash, 'couse it can't finde the more or less "null" strings :( . May you have an other idea?

**Comment by tom-englert** [comment]
So how would you distinguish entries that you can remove from entries that you can't?

**Comment by tom-englert** [comment]
@McOldSchool did you find a reliable criteria to detect the entries that can be removed?

**Comment by McOldSchool** [comment]
Ah sorry wasn't around for a bit. Yea for my understanding the neutral language is kept up-to-date from MS so if translatable values getting change they are removed from the 'main'-resx file but not from the translated one.
So it should be possible to check the translatable-values from the translated files against the 'main' one and if the value dosn't exist anymore, delete it.
This would also work with 'empty' strings in the 'main' file, because the tag is there still available (just empty) so those won't get deleted.

On the other side I was thinking about this issue during the week and as there is a special 'highlighting' for rows which haven't got a language file yet, may it's possible to have some similar highlight if there is no more related tag in the 'main' resx file?

**Comment by tom-englert** [comment]
A simple out-of-the-box solution would be to switch to cell selection and delete all cells right to the neutral language where there is no entry in the neutral language. 
This will not touch the neutral language...

**Comment by McOldSchool** [comment]
Ahh. Sometimes it's just easier than expected.
I'd be fine if you want to close it. (As long as there is no inspiration for any other feature in it :D )

Keep up the good work! And cheers!

**Comment by tom-englert** [comment]
😄
