### ISSUE TITLE
"Neutral" column header not reflecting langusge setting

### ISSUE THREAD

**Issue by knutt** [tom-englert/ResXResourceManager#55]
The VS add-in does not reflect the neutral language selected in the header of the "Neutral" column.

In the AssemblyInfo.cs file, you can set the neutral language for an assembly:
`[assembly: NeutralResourcesLanguage("nn-NO")]`

However, no matter how this is set, an American flag is flying over the column. This is misleading. Either the flag of the neutral culture should be used, or the flag should be omitted for this column.

**Comment by tom-englert** [comment]
Unfortunately assembly attributes are not available in .resx files, and ResXManager can't not compile your source code to detect this...

If you derive from the standard "en-US", you have to change the default in the configuration page of ResXManager.
