### ISSUE TITLE
Feature Request: Configurable validation 

### ISSUE THREAD

**Issue by Llarian** [tom-englert/ResXResourceManager#56]
Could you add a validation that, like the validation of string format parameters, checks the usage of characters like pipes or other configurable character(s)?

**Comment by tom-englert** [comment]
How could we check the usage of pipes?

**Comment by tom-englert** [comment]
@Llarian any feedback what exactly you mean with this?

**Comment by Llarian** [comment]
Currently there is a validation regarding the usage of string format parameters: you get a warning if the number of parameters used differs from one language to another. I'd also liked a warning for the usage of pipes: When used in a FileopenDialog in the filter string to seperate the values, .NET will throw an exeption, in case the pipe is missing. Our translators do not all know the importance of pipes and we (developers) do not check the translations of languages we don't know. 
For this it might be useful to set the "source" language, which is the developers own language; this will most probably be correct. The "tartet" languages should be checked against the source language.

This is a very specific example, but I gues there might be other scenarios. So something configurable would be the best solution.

**Comment by tom-englert** [comment]
Unlike common string format parameters, this is a very special use case.
I would rather recommend not including the pipes in the resources at all, but only the translatable part(s).
