### ISSUE TITLE
DNN Tokens

### ISSUE THREAD

**Issue by nmamanx** [tom-englert/ResXResourceManager#6]
Hello,
What is the Regex to be adding for supporting "dotnetnuke tokens"?,
And what are the configuration for it?
Adding same example\links:
dnn tokens:  http://www.dnnsoftware.com/wiki/tokens
Regex for dnn tokens:  \[(\w+|\W*?:\w+|\W*?)*\]  (it is o.k?)
Example for tokens:
[Portal:Currency]
[Portal:Description]
[Portal:Email]
[Portal:FooterText]
[Portal:HomeDirectory]
[Portal:LogoFile]
[Portal:PortalName]
[Portal:PortalAlias]
[Portal:TimeZoneOffset]
[User:DisplayName]
[User:Email]
[User:FirstName]
[User:FullName]
[User:LastName]
[User:Username]
[User]
[number]

Thanks,
Nir

**Comment by tom-englert** [comment]
I assume you are talking about "Detect Code References" configuration, right?
But how would that tokens map to the keys in the resource files?

**Comment by nmamanx** [comment]
did not worked.
[User] , did not work at all
[User:Username] , first word translated. only the second did not translated.

**Comment by nmamanx** [comment]
a good regex for dnn tokens:
\[(\w+)\]|\[(\w+:\w+)\]
but still did not working good :(

**Comment by tom-englert** [comment]
I'm not sure what you are talking about.
* I assume you are talking about "Detect Code References" configuration, right? Or is this question about how to use resx with dnn tokens in general?
* But how would that tokens map to the keys in the resource files?  How will this dnn tokens access the resources?

**Comment by tom-englert** [comment]
@nmamanx can you please clarify what this issue is about?

**Comment by tom-englert** [comment]
Close issue since I still have no clue what this is about, and no reply from @nmamanx
