### ISSUE TITLE
VS2017 Update 5 causing ResXResourceManager window to not load

### ISSUE THREAD

**Issue by jamesmcroft** [tom-englert/ResXResourceManager#62]
After recently updating to the latest VS 2017 update, ResX Manager has stopped loading in the resources from the files in my projects.

Some files are loaded and appear in the left-hand sidebar but when clicking on them to view the resources, the keys are shown in a column but has an un-headered column next to it with nothing in.

**Comment by tom-englert** [comment]
Maybe you are using lazy solution loading? RXRM can only show items of loaded projects.

**Comment by tom-englert** [comment]
@jamesmcroft any more details on this?

**Comment by jamesmcroft** [comment]
@tom-englert apologies for not getting back in touch sooner. 

The project is not lazy loaded. I haven't checked for output error messages but can do that. 

I'm currently away from my office PC but will be returning on the 2nd January so can confirm then.

**Comment by halllo** [comment]
When I click on `Tools/ResX Manager` nothing happens. When I `Ctrl+Tab`, I see that it is there as an Active Tool Window but when I navigate to it, nothing is visible and I dont see that window anywhere. `Reset Window Layout` also did not help. I am using Visual Studio Community 2017 Version 15.5.2.

The output looks good:
```
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: C:\Users\manue\AppData\Local\Microsoft\VisualStudio\15.0_c57bfe68\Extensions\xwlljq3w.5vf
Version: 1.11.893.0
```

**Comment by tom-englert** [comment]
Just updated my VS and everything still works fine. There are no special prerequisites needed. 

Maybe checkout this: https://github.com/remcoros/DuplicateExtensionFinder, updating extensions sometimes leaves duplicates behind that confuse VS.

**Comment by halllo** [comment]
The Window appeared off screen. I see it now and all is good.

**Comment by jamesmcroft** [comment]
I think this can be closed off @tom-englert. The latest, latest version of VS2017 15.5.2 seems to be working fine. Must have been an issue with my setup.
