### ISSUE TITLE
Add more RegEx options to the "Detect Code References"

### ISSUE THREAD

**Issue by UweKeim** [tom-englert/ResXResourceManager#64]
For the "Detect Code References" list of Regular Expressions, I'm looking for other RegEx options.

Several of  the string occurrances in my code span multiple lines like:

    Resources.
        My_Very_Long_Resource_Name

Therefore, I'm looking for more than just the "Case Sensitivity" options.

Maybe you could add another text column to enter Perl-style RX flags. 

I.e. one or multiple of:

- `i` — Case-insensitive
- `x` — Ignore pattern whitespace
- `m` — Multi line
- `s` — Single line

Thus entering something like `im` would make it case-insensitive and multi line.

--------

Alternatively, how about adding at least two more check boxes for "Multi line" and "Single line".

**Comment by tom-englert** [comment]
It's not a matter of the regular expression (https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-options), but the file parser. 
If s.o. can provide a solution that is fast, language agnostic *and* can support multiple lines, I'll be happy to integrate it.

**Comment by tom-englert** [comment]
Duplicate of #19

**Comment by UweKeim** [comment]
Thanks, @tom-englert and sorry for not doing a better search before posting here 😞.

Personally, I don't care about speed for this feature, so I'm happy with a slow solution, too (maybe warn the users that this is slow, so they don't complain).
