### ISSUE TITLE
Opening an exported excel file

### ISSUE THREAD

**Issue by tmslammi** [tom-englert/ResXResourceManager#65]
Hi,

Should it be possible to open an exported excel file in the desktop application? I used the VS plugin to export my .resx files to excel format, and after that tried to import that file using the desktop application. Nothing is shown, and no errors / warnings are produced in the output window. Should this be supported? I can't really find anything about it in the documentation.

**Comment by tom-englert** [comment]
Yes, that works fine. However you won't see anything unless you modify the Excel file before importing.

**Comment by tmslammi** [comment]
Hi,
Would it be possible to load the file even without doing modification for it beforehand :)?

**Comment by tom-englert** [comment]
Well, it is, that's what you already tried - if you import no changes, nothing will be changed, and you will see nothing change, it's the same as doing nothing at all.

**Comment by tmslammi** [comment]
Sorry If I am misunderstanding the usage of this tool, but I'm having trouble to get this to work for my use case which is:
1. Load all the .resx files using VS and export the excel file

2. Send this excel file to a translator, who would either edit it excel (this works fine) OR using the desktop application you provide

3. Using the desktop application to import the excel and do the translation work without having access to the source code or not having visual studio, then export that and send it back to someone who will import it back to the solution.
 **Using the desktop application, I have not been able to open the excel file so that the translator would be able to use it to do the translations, without having access to the source code or not having visual studio.**

Am I doing something that is not supported here?

Thanks in advance

**Comment by tom-englert** [comment]
You can't open an excel file, you only can import it into an existing structure. 
ResXManager standalone can only open a folder containing a solution. However you will need only the .resx and the .??proj file, not the full source code.

**Comment by tmslammi** [comment]
Okay, thanks for the quick responses and the information :)
