### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by xan2622** [tom-englert/ResXResourceManager#68]
Could you please add a horizontal scrollbar? 
It would be useful when there are many resource files loaded from a folder. 

I think a horizontal scrollbar is needed especially because when the user changes dimensions of the window, columns' widths are modified on the fly...    :-/

![screenshot001](https://user-images.githubusercontent.com/1732773/34861255-dee2d10a-f763-11e7-8ccc-47dd8c084197.png)

**Comment by tom-englert** [comment]
It will appear automatically as soon as you exceed the columns beyond the right edge
