### ISSUE TITLE
Empty main view 

### ISSUE THREAD

**Issue by DRESAAN** [tom-englert/ResXResourceManager#72]
My main view is empty. Every other Tab is working. I get the following exception during start:

> `ResX Resource Manager wurde geladen.
Webseite: https://github.com/tom-englert/ResXResourceManager
Fehler melden:  https://github.com/tom-englert/ResXResourceManager/issues
Projekt unterstützen: Schreiben sie ein kurzes Review auf https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Fehler: System.Windows.Markup.XamlParseException: Die Auflistungseigenschaft "Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger"."Actions" ist NULL. ---> System.Xaml.XamlObjectWriterException: Die Auflistungseigenschaft "Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger"."Actions" ist NULL.
   bei System.Xaml.XamlObjectWriter.WriteGetObject()
   bei System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   bei System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   bei System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   bei System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   bei System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   bei tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml:Zeile 1.
   bei tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ICompositionHost compositionHost) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:Zeile 55.
Installationsverzeichnis: C:\Users\brandhoff\AppData\Local\Microsoft\VisualStudio\15.0_0bb60e60\Extensions\udfoiuu4.koq
Version: 1.11.893.0
`

**Comment by tom-englert** [comment]
Looks like there is some incompatible version of "Microsoft.Expression.Interactivity" loaded.

**Comment by DRESAAN** [comment]
I checked my fusion log. There is no assembly with the name Microsoft.Expression.Interactivity but one with the name Microsoft.Expression.Interactions. But this is binded without any problems and only in one version.

But two versions of System.Windows.Interactivity get binded. The other one is only loaded from the resharper installation path.

**Comment by tom-englert** [comment]
Does temporary disabling R# fix it?

**Comment by DRESAAN** [comment]
I deactivated all Extensions which did not come from Microsoft and it still doesn't work.

**Comment by tom-englert** [comment]
So now there is only one System.Windows.Interactivity, and this is loaded from the ResXManager folder?

**Comment by tom-englert** [comment]
Does someone have software from Telerik installed? I think there has been some problems in the past..

**Comment by niketgosrani** [comment]
We don't have Telerik installed but we have its assemblies in our Debug folder and also already tried the above resolutions and still does not work.

**Comment by niketgosrani** [comment]
We removed all the Telerik dlls and it still does not work. The following exception is thrown in Output window 
`
Error: Loader errors at start:
Assembly: Microsoft.Expression.Interactions.dll => Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.: 
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Error: System.Windows.Markup.XamlParseException: The method or operation is not implemented. ---> System.NotImplementedException: The method or operation is not implemented.
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType bamlType, Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16 typeId)
   at System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   at System.Windows.Baml2006.Baml2006Reader.Read()
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml:line 1
   at tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ICompositionHost compositionHost) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:line 55
Assembly location: C:\Users\ngosrani\AppData\Local\Microsoft\VisualStudio\15.0_75079540\Extensions\oquiejlc.vbf
Version: 1.11.893.0`

**Comment by tom-englert** [comment]
@DRESAAN, @niketgosrani 
I still have no feedback on this: are both `System.Windows.Interactivity.dll` and `Microsoft.Expression.Interactions.dll` only loaded once and only from the ResXManager folder, or are there multiple instances or loaded from different locations?

**Comment by niketgosrani** [comment]
I am at least aware of using "System.Windows.Interactivity.dll" in our project and it comes from our local on the machine and use version (3.0.40218.0) and also "AppData\Local\Microsoft\VisualStudio\15.0_75079540\Extensions\oquiejlc.vbf" this installs the older version. Also, the plugin for ResX manager installs the older version of "System.Windows.Interactivity.dll" (2.0.20525.0). This same is set up on my colleagues' machine and it works for them.

**Comment by tom-englert** [comment]
@DRESAAN @niketgosrani 
I have the same here, except that Microsoft.Expression.Interactions is not from GAC but from the ResXManager folder.

Can you check what version of .Net Framework you have installed on your machine?

**Comment by DRESAAN** [comment]
I had a quick look at the versions. Looks like I have the versions 2.0.5xxxx, 3.0, 3.5, 4.0 and 4.6.2

**Comment by tom-englert** [comment]
This could be the reason - there was a fix for WPF targeting such issues in 4.7.1

**Comment by tom-englert** [comment]
Fixed in 1.15
