### ISSUE TITLE
Resource files from the project not loaded.  #helpwanted

### ISSUE THREAD

**Issue by ArunaG1** [tom-englert/ResXResourceManager#73]
Hi Tom

I have run the project solution and got the below output

![image](https://user-images.githubusercontent.com/30783149/35317538-39cdfffc-00fd-11e8-8170-44fa6abf6480.png)
#help  @wanted

On load will it load the resource files from the project? or we have to select the path of the resource files from the project?

Thanks

**Comment by tom-englert** [comment]
If you use the standalone version, you have to select the directory where the solution is - click on the directory menu to select it.

If you use Visual Studio Extension from within Visual Studio, the resources of the active solution are automatically loaded.
