### ISSUE TITLE
PowerShell Script Error "Add-Type : Could not load file or assembly"

### ISSUE THREAD

**Issue by rbrinson** [tom-englert/ResXResourceManager#74]
I am trying to get the basic Sample.ps1 script working, but I am running into errors immediately in the script. The error is:
> Add-Type : Could not load file or assembly
> 'file:///C:\Users\rbrinson\Development\ResxResourceManagerScripting\ResXManager.Scripting.dll' or one of its
> dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
> At C:\Users\rbrinson\Development\ResxResourceManagerScripting\GveResxUpdate.ps1:8 char:1
> Add-Type -Path $resxAssembly
> CategoryInfo          : NotSpecified: (:) [Add-Type], FileLoadException
> FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.AddTypeCommand

Obviously, all of the DLLs from the Scripting.zip file exist in the same folder as was referenced above. Because PowerShell fails to load the ResXManager.Scripting.dll, it fails to create the new object of type ResXManager.Scripting.Host. I have tried running the script as Administrator with the same result. I have tried using the DLLs from both version 1.11 and 1.10 with the same results.

I have both Visual Studio 2015 and Visual Studio 2017 installed, and I have installed both the stand-alone ResXResourceManager application as well as the Visual Studio Extension in VS2017. According to the output of $PSVersionTable.PSVersion, I have PowerShell version 5.1.14393.1944 installed on Windows 10 Enterprise, 64-bit. According to my system registry, I have the following version of the .NET Framework installed v2.0.50727, v3.0, v3.5, v4, v4.0, v4.5, v4.6, and v4.7.

Am I missing something? Does the scripting piece need to be located in a specific folder? Does it require a specific version of the .NET Framework or PowerShell? I am at a loss as to how to proceed, and the scripting aspect of the ResXResourceManager tool is desired for our CI build process. Thanks in advance for any insight you can offer.

**Comment by tom-englert** [comment]
All the scripting binaries from the .zip must be in the same folder. There is no other dependency.

You might have to unblock the files if you have extracted the zip with windows explorer.

**Comment by rbrinson** [comment]
@tom-englert, thank you for your reply. I am new to working with PowerShell, and you were correct that the assemblies needed to be unblocked in order for PowerShell to load them. It would be nice if the PowerShell error message were a bit more helpful in understanding that this was the case.
