### ISSUE TITLE
Scripting: Imported Excel Values Not Persisted to RESX Files

### ISSUE THREAD

**Issue by rbrinson** [tom-englert/ResXResourceManager#77]
I have been trying to develop a workflow as part of our CI process that would take an Excel spreadsheet of new and/or updated translated string values for the languages we support and incorporate those changes into our existing RESX files. The Excel spreadsheet was actually created using ResXResourceManager, and the format for each sheet (a typical sheet name would be Extron.GVE.Localization|About) is as follows:

Key                 |                                       | ru-RU                                       | zh-CN
--------------- | ------------------------- | --------------------------------- | ----------
InvalidFormat | The format is not valid. | Недействительный   формат | 格式无效

I have tried importing the changes using the ResXManager.Scripting library and a modified Sample.ps1 PowerShell script. The script looks like the following:

```
$excelFileName = 'C:\Users\rbrinson\Development\Web\GVE\Extron.GVE.Localization\ResxUpdates.xlsx'
$solutionFolder = 'C:\Users\rbrinson\Development\Web\GVE'

Add-Type -Path 'ResXManager.Scripting.dll'
$myhost = New-Object -TypeName 'ResXManager.Scripting.Host'

$myhost.Load($solutionFolder)

$allCultures = $myhost.ResourceManager.Cultures
$allCultures

$fileName = $baseName + $cultureName + ".resx"
$neutralCulture = ""
$outputCulture = ""

$allEntries = $myhost.ResourceManager.TableEntries

"All entries: " + $allEntries.Count

"Importing modified excel file"
$myhost.ImportExcel($excelFileName)
$myhost.Save()

Read-Host "Done" | Out-Null
$myhost.Dispose()
```

While I did not receive any errors, the new values introduced in the Excel spreadsheet were not in the RESX files at the end of the process. I then cloned your GitHub repository locally and created a unit test to exercise the _ImportExcel_ and _Save_ methods. The code executed correctly, finding the changes in the Excel spreadsheet tabs and applied those changes to the entities in memory. However, when the _ResXManager.Model.ResourceManager.Save_ method is called, the _Languages.HasChanges_ property comes back as false, and in the end the array that is holding the _ResourceLanguage_ instances is empty. So, the _ResXManager.Model.ResourceLanguage.Save_ method is never called. My unit test code looks like the following:

```
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ResXManager.Scripting.UnitTests
{
    [TestClass()]
    public class HostTests
    {
        private Host resxManager;
        private string solutionFolder = @"C:\Users\rbrinson\Development\Web\GVE";
        private string excelFileName = @"C:\Users\rbrinson\Development\Web\GVE\Extron.GVE.Localization\ResxUpdates.xlsx";

        [TestInitialize()]
        public void InitializeTest()
        {
            resxManager = new Host();
        }

        [TestMethod()]
        public void ImportExcelTest()
        {
            try
            {
                resxManager.Load(solutionFolder);
                resxManager.ImportExcel(excelFileName);
                resxManager.Save();
                Assert.IsTrue(true);
            }
            catch (Exception e)
            {
                Assert.IsTrue(false, "Failure: " + e.Message);
            }
        }
    }
}
```
Did I miss something in this process? What more do I need to do in order for the changes to be persisted to the RESX files?

**Comment by ilengyel** [comment]
@rbrinson this looks like the same issue as I had in #76. There I mentioned the workaround I used where the current dispatcher is forced to empty its queue before calling the save method. In your case you could try porting the `DoEvents()` method mentioned in #76 to powershell and call it before calling `host.Save()`

**Comment by rbrinson** [comment]
@ilengyel , I added the DoEvents() code you proposed to my unit test code in order to see if I got better results, and it does work. After running through the code, my RESX files are properly updated. @tom-englert does this mean that the Sample.ps1 is broken as it is currently scripted?
