### ISSUE TITLE
Language is not defined

### ISSUE THREAD

**Issue by michaelhutchful** [tom-englert/ResXResourceManager#78]
I am building a UWP and and I want to be able to right click a string and move to resource. However I get Language is not defined. 
I have a manually created a resource file that is loaded in Resx manger

**Comment by tom-englert** [comment]
Can you post a sample project?

**Comment by michaelhutchful** [comment]
https://github.com/michaelhutchful/resxtest.git 
This is a UWP app targetting the fall creators update(16299). I have been able to recreate the problem. In main.xaml.cs there is a string "dummy string". Right clicking and moving to resource throws the error, Language not defined. Thanks for your quick reply.

**Comment by michaelhutchful** [comment]
Hi, I tried the extension from here http://vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a/ but I still have the same issue, do I need to wait for an update to showup in the marketplace?

**Comment by tom-englert** [comment]
That should work, just make sure you always have a resource that matches the neutral language (en-US by default)

**Comment by michaelhutchful** [comment]
It is working now on the sample project I sent, I think it has to do with my dev project. Thank you so much.

Sent from Mail for Windows 10
