### ISSUE TITLE
Move to resource generate wrong code in Attribute

### ISSUE THREAD

**Issue by cuoilennaocacban** [tom-englert/ResXResourceManager#82]
For example, I have a property decorated with some attributes like ```[Display(Name = "Local text")]```
When using the extension, it automatically generate code to ```[Display(Name = ResourceClass.ResourceKey)]```
But for it to work properly, the code must be ```[Display(ResourceType = typeof(ResourceClass), Name = "ResourceKey")]```

It would be perfect to support this feature, since a lot of text need to move to resource out there live in Attributes

**Comment by tom-englert** [comment]
You can configure the patterns to your needs. 
You can also switch the code generator to "Text template" and use the `LocalizedDisplayName` attribute that provides type-safe usage.

**Comment by cuoilennaocacban** [comment]
thank @tom-englert ,
for those who stumble upon this, here is the exact patterns
```
|nameof($File.$Key), ResourceType = typeof($File)|ErrorMessageResourceType = typeof($File), ErrorMessageResourceName = nameof($File.$Key)
```
