### ISSUE TITLE
Possibility to use File name in XAML for code generation ?

### ISSUE THREAD

**Issue by oschwab** [tom-englert/ResXResourceManager#84]
Hello,

Inside Xaml I would like to use something like $FileName in Move To Resource.
So that in File MainWindow.xaml , my generated code looks like { ..  MainWindow.Key}.

Is it possible ?

**Comment by tom-englert** [comment]
No, what would be the use case?

**Comment by oschwab** [comment]
Alongside WpfLocalizationExtension, I plan to use one-file-per language strategy . To differentiate windows resource ID, I would le to use the Window name (i.e filename) as prefix  [as shown in this image](https://i.imgur.com/rcQ3Ebz.png). (I hope it is more clear now)

**Comment by tom-englert** [comment]
Added in 1.24
