### ISSUE TITLE
Remove keyboard shortcut specifier ('&') in strings before translating

### ISSUE THREAD

**Issue by dahall** [tom-englert/ResXResourceManager#93]
When a string contains a keyboard shortcut indicator, it generally causes the translation engines to produce poor results. For example, Azure fails to translate "T&asks", but can successfully translate "Tasks". A simple regular expression could be used to remove those '&' values before sending the service.

**Comment by tom-englert** [comment]
Should also remove '_', this is used e.g. by WPF applications.
