### ISSUE TITLE
Google Translate & MyMemory incorrectly translating to zh-hans (simplified) when request zh-hant (traditional)

### ISSUE THREAD

**Issue by brettwinters** [tom-englert/ResXResourceManager#95]
Hello

I have an issue. I set the name of the resource file to: "xxxx.zh-hant.resx" (my base is en-US)
When running translate using both google and MM, both translate to zh-hans on the stand-alone version of this software

For example: 
"Please Sign In" should output "請登錄" (zh-hant), but in fact output "请登录" (zh-hans) 

Note: Using https://translate.google.com/m/translate#auto/zh-TW/Please%20Sign%20In works successfully.

![image](https://user-images.githubusercontent.com/26474006/37252145-ec32acf4-254e-11e8-9297-dc6af5f6a769.png)

![image](https://user-images.githubusercontent.com/26474006/37252153-199dcad4-254f-11e8-9bef-e72d04aea347.png)

**Comment by tom-englert** [comment]
I have already tried with MM (#30), but found no way get the correct output.
However for Google there seems to be special handling needed: https://cloud.google.com/translate/docs/languages. 
@dahall can you add these special cases?

**Comment by brettwinters** [comment]
following the link, it seems that the two Chinese scripts need to follow the tag-subtag-code system of BCP-47 naming system which is:

![image](https://user-images.githubusercontent.com/26474006/37254411-fe0ebf8c-256f-11e8-8911-dbf55bfa01f2.png)
(from here: https://cloud.google.com/speech/docs/languages)

Unfortunately, if I use this system the resource file is not recognised. Also using zh-HK/TW (both traditional scripts doesn't work either - both default to zh-hans)

@tom-englert did you use another tool to handle the Chinese script issue?

**Comment by tom-englert** [comment]
The free Azure service does it right.

MyMemory:
`https://mymemory.translated.net/en/English/Chinese-Traditional/Please-Sign-In`
click on "API call"
=> `https://api.mymemory.translated.net/get?q=Please Sign In&langpair=en|zh`
And no matter what Chinese variant you specify as target language, you get always the same result.

Google may be able to handle this, but needs some extra coding. However I don't have an account, so I can't do it.

**Comment by dahall** [comment]
@brettwinters - Just to be specific Google Translate only support traditional and simplified Chinese. I have updated the code such that zh-hant, zh-cht, zh-hk, zh-mo and zh-tw all point to traditional and any other Chinese variant points to simplified. Please correct any of this if you know better.

**Comment by dahall** [comment]
Also, for documentation purposes, Google supports Cebuano and Hmong as languages, but I have left them out as I could not find equivalent .NET CultureInfo equivalents.

**Comment by brettwinters** [comment]
I checked with my Chinese friend and he assured me there are only two scripts (although the spoken words would depend on the language)

Thanks so much for your help. This utility is really a godsend!
