### ISSUE TITLE
V 1.12 Visual Studio Community 2017 15.6.1 Build Hangs

### ISSUE THREAD

**Issue by DominicRich** [tom-englert/ResXResourceManager#97]
I don't know if this is purely because we have so many missing translations (9600 or so), but the latest release with the latest update of VS2017 causes VS to hang for around two minutes before every build. Is this a new feature? If so, can it be optional?
This is feature request #28

**Comment by aitorhdez** [comment]
Hi,
The same for me. 'Missing translation' warnings seem to collapse build process on Visual Studio 2015 (about 12000 messages) There is a way to disable warnings for ResX Manager?
Thanks

**Comment by wansor** [comment]
Same problem here. Please turn this “feature” off by default. I succeeded one to open the configuration page and turn it off, but I never succeeded to go back to that page. A co-worker never got there. So we had to revert to the previous version.

**Comment by dingjimmy** [comment]
Visual studio auto updated the extension for everyone on the team i work on this morning and this issue nocked us out for the entire for a day. I can confirm that disabling the feature as suggested has worked for us and we are now back up and running again.

**Comment by BlagoCuljak** [comment]
Hello, we are also having same issues, VS2017, even clean hangs VS, if I wait 5min it does what it should.

Hope Tom is reading this.

**Comment by tom-englert** [comment]
I see, so I will change the default to "off". 
May take some days until I find time to publish the new release...

**Comment by DominicRich** [comment]
@tom-englert I didn't realise you could turn this off in the configuration (thanks @aitorhdez ).
This does solve the issue. You may want to turn it off by default unless you could put something in the output window which stated it was checking and warned about performance? I think this can be closed given that it can be turned off.

The solution is to go into the configuration tab (at the bottom of the window) and uncheck "Show messages in error list"

**Comment by tom-englert** [comment]
Reopen to avoid people adding too many duplicates

**Comment by madskristensen** [comment]
@tom-englert It looks like it happens in this method https://github.com/tom-englert/ResXResourceManager/blob/master/ResXManager.VSIX/ErrorProvider.cs#L90 when you add tasks to the collection. It may be fixed simply by calling TaskProvider.SuspendRefresh() before you modify the collection and TaskProvider.ResumeRefresh() afterwards
